### PR TITLE
Naive projector prioritization

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
See issue #3426 for a better solution.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please review later (projector code just moved).

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please add CHANGELOG entry before merge.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Done

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
