### PR TITLE
Update saml-setup.sh

### PR DESCRIPTION
**Pull request by ManniLoe**
If the server container is restarted e.g. after OS reboot, the saml-setup.sh script fails because the symbolic links to SP Crt / Key / Settings already exist.

### CODE REVIEW

**Comment by ManniLoe** [comment]
see #5581

**Comment by gsiv** [comment]
Thank you.  Would you mind adding an English language commit message?

Afterwards, the commit can be merged.

**Comment by ManniLoe** [comment]
> Would you mind adding an English language commit message?
I added an English commit message

**Comment by FinnStutzenstein** [comment]
Note to the person who will merge this PR: Use a squash merge for merging.

**Comment by ManniLoe** [comment]
ping

**Pull request merged**
