### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
@ostcar Can you have a look at this please?

**Comment by ostcar** [comment]
on a short look, It seams ok. Be careful when you use asyncio.Lock. It is not Thread-Safe and it django channels starts new thready every time async_to_sync is called. Since we use async consumers, I think django channel does not call async_to_sync in this case.

**Comment by FinnStutzenstein** [comment]
@ostcar You are right. I'll do some more research about the actual usage of threads by asyncio and channels to check, if async requests (http as well as WebSocket -> channel message handing) uses one thread or a threadpool. Or do you have a good place to look this up?

**Comment by ostcar** [comment]
I don't know. You could search for async_to_sync in the channels, channels-redis and daphne code

**Pull request merged**
