### PR TITLE
fixes #3173

### LINKED ISSUE #3173: Agenda text cannot be saved
When I enter some text in the agenda text field, the text cannot be saved and always changes back to `['text']` (in html source code: `<p>[&#39;text&#39;]</p>`). In motions or elections, the text or description fields are working fine. 

image

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Important! Does this can be included into the 2.1? This is a blocker..

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Please add CHANGELOG entry.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel ping

**Comment by emanuelschuetze** [comment]
@normanjaeckel Ping. Please merge this pull request also in a new stable branch that we can make a 2.1.1 release next days.

**Comment by normanjaeckel** [comment]
The branch split up will be done later. I will care about this ...

**Pull request merged**
