### PR TITLE
Updated API for plugins.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Ok. But travis failed:
```
$ flake8 openslides tests
openslides/utils/plugins.py:4:1: F401 'import_module' imported but unused
```
You can merge it after travis is fixed.

**Comment by emanuelschuetze** [comment]
@normanjaeckel ping, please merge if ready

**Comment by emanuelschuetze** [comment]
Travis is fixed. So I'll merge it now.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
