### PR TITLE
Fixes problems with config.key_to_id

### PR DESCRIPTION
**Pull request by ostcar**
Make the projector-system explicit async to call async functions

Also lock config.build_key_to_id

### CODE REVIEW

**Comment by ostcar** [comment]
You don't have to flush redis. Please test again.

**Comment by emanuelschuetze** [comment]
I retested. Same error after server restart (I keep the clients without reload; just restart server):

```
WebSocket HANDSHAKING /ws/ [127.0.0.1:53342]
Exception inside application: 'NoneType' object is not subscriptable
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/sessions.py", line 179, in __call__
    return await self.inner(receive, self.send)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/utils.py", line 52, in await_many_dispatch
    await dispatch(result)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/generic/websocket.py", line 175, in websocket_connect
    await self.connect()
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/consumers.py", line 33, in connect
    if not await async_anonymous_is_enabled() and not self.scope["user"]["id"]:
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/auth.py", line 162, in async_anonymous_is_enabled
    (await config.async_get_key_to_id())["general_system_enable_anonymous"],
  'NoneType' object is not subscriptable
WebSocket DISCONNECT /ws/ [127.0.0.1:53342]
```

If I reload my both client tabs the server error is gone... But we have no control about all browser connectoins and cannot ask all users to reload... Any other idea to fix it  -without flushing redis?

**Comment by ostcar** [comment]
I can not understand, how this is possible. This part of the code has nothing to do with the connected clients.

How do you restart the server without reconnecting the clients? When you restart the server, all clients have to reconnect. So please explain farther what you are doing.

**Comment by emanuelschuetze** [comment]
- stop server (clients gets offline message)
- start server (client reconnect)
- server shows "toggeling" log messages between HANDSHAKING/DISCONNECT  -> error
- reload client (F5) -> server shows correct HANDSHAKING without error

**Comment by ostcar** [comment]
ok I found another typo... Someone should write more tests...

**Comment by ostcar** [comment]
I think the mix async and sync code, that django channels provides is broken. The async-package is not thread safe. It says so many times in the docs. But django channels creates a lot of threads when calling async_to_sync. So when you use an API in a way that the documentation says, you should not use it, then you should expect errors.

In this case, it has nothing to do with it. But it is nearly impossible to be sure, there are no race conditions. So the error, above could still happen in rare cases.

**Comment by emanuelschuetze** [comment]
@ostcar Can you please rebase and solve the conflict in core/config.py? Thanks.

**Comment by ostcar** [comment]
done.

I errors happens, there are probably missing await or async statements

**Pull request merged**
