### PR TITLE
Minimum amount of votes

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
renamed votes_amount to max_votes_amount

@tsiegleauq The client has to be adopted. I added both `min_votes_amount` and `max_votes_amount` and adjusted basic places. But the validation is missing in two places: In the poll form, `max_votes_amount` must be greater or equal than `min_votes_amount` (some custom validation). While voting, the check, if at least `min_votes_amount` votes were selected is missing.

### CODE REVIEW

**Comment by tsiegleauq** [comment]
rebased quite heavily, fixed typos, still a lot of bugs.

**Comment by FinnStutzenstein** [comment]
Ok, whats the state here? I see the python tests are failing - I'll have a look. Is the client ready?

**Comment by tsiegleauq** [comment]
> Ok, whats the state here? I see the python tests are failing - I'll have a look. Is the client ready?

same as above. WIP, client is not done, server tests are failing, prolly due to new features.

**Comment by FinnStutzenstein** [comment]
The server should be fixed now. Attention: I rebased on master again.

**Comment by tsiegleauq** [comment]
@emanuelschuetze @FinnStutzenstein can be tested

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Tested:
- add hint about min votes behind "Available votes" (if min votes > 1) -> e.g. election with 4 candidates and min votes=2, max votes=4. The user has to know why after 1 vote (3/4 available) sending of ballot not possible...
- remove 'min/max votes' fields for _analog_ voting
- remove 'general approval/rejetion/abstain' for _analog_ voting

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
