### PR TITLE
Supported server side setup of new agenda items (type and parent).

### PR DESCRIPTION
**Pull request by normanjaeckel**
@FinnStutzenstein First step here. Now we can implement the client sending extra fields like type and parent on creation of agenda related items like motion, motion block, topic and assignment. Do you want to do some things here like changeing client for e. g. assignment. Then we can go on with the server ...

See #3016, #2886, #2779.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@normanjaeckel If you create an assignment the field `agenda_type` and `agenda_parent_id` will be in the request data. On an update just the `agenda_type`will be provided. The server has to check the permissions to set this field. If this is OK, I will remove all uncommented stuff and change topics and motions.

**Comment by normanjaeckel** [comment]
I prefer that we remove all agenda related stuff from the all update forms. (At the moment the form does not reflect the database status properly (the form field refers to 'is_hidden' and not to 'type') So we should offer this feature only for create views. @emanuelschuetze?

**Comment by FinnStutzenstein** [comment]
OK for me, @emanuelschuetze ?

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please let us discuss about this pr.

**Comment by emanuelschuetze** [comment]
> I prefer that we remove all agenda related stuff from the all update forms.

+1 (as discussed with @normanjaeckel)

**Comment by normanjaeckel** [comment]
@FinnStutzenstein Please review and finisch assignment app (remove form fields in update form etc.).

**Comment by normanjaeckel** [comment]
Note for me:
* MotionCreate, MotionUpdate
* The same for MotionBlock
* The same for Topic

**Comment by normanjaeckel** [comment]
@FinnStutzenstein Ready for next test (I had only some time for a short test.). Please also have a look at my changes on the client.

Maybe we also have to fix TopicImport. Any idea here?

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Works fine for me with topics, motions, motion blocks and assignments. Just one request during creation and no agenda related settings in the update forms. With my last commit, this should be ready to merge.

**Comment by normanjaeckel** [comment]
I fixed topic import. So please retest (also topic import). Then merge.

**Comment by emanuelschuetze** [comment]
Fixed travis (missing semicolon).

**Pull request merged**
