### PR TITLE
Catching a number, if not a number

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**

### CODE REVIEW

**Comment by GabrielInTheWorld** [comment]
@CatoTH Please review. There exists an issue with the `diff.service.ts`, if the user pastes HTML-code in the code-editor of the application.
The changed lines catches the error, but the tests fail.

**Comment by CatoTH** [comment]
@GabrielInTheWorld I'm not sure I can reproduce this right now. What exactly do I have to paste in the code-editor? (I assume, you're using the source code view of the editor to paste it?)

**Comment by GabrielInTheWorld** [comment]
The answer of your two questions is: yes.
You can, for example, paste the following code into your editor:

<div class="motion-text motion-text-diff amendment-view line-numbers-outside ng-star-inserted"><h3 class="amendment-line-header ng-star-inserted"> Zeile 8 - 9: </h3><div class="paragraphcontext"></div><div><p><span class="os-line-number line-number-8" data-line-number="8" contenteditable="false">&nbsp;</span>Mit einem richtig langen Text wird der Kuchen doch bestimmt der beste von allen <del>sein, oder </del><br class="os-line-break"><span class="os-line-number line-number-9" data-line-number="9" contenteditable="false">&nbsp;</span><del>was sagen sie dazu?</del><ins>sein?</ins></p></div><div class="paragraphcontext"></div></div>

**Comment by emanuelschuetze** [comment]
@tsiegleauq Maybe you can review if we still need this PR.

**Comment by tsiegleauq** [comment]
would wait for #5304

**Pull request closed without merging**
