### PR TITLE
Add number_value to motion model.

### PR DESCRIPTION
**Pull request by reiterl**

### CODE REVIEW

**Review by jsangmeister — DISMISSED** [review]
Please add a description.

**Comment by FinnStutzenstein** [comment]
This should also be flagged as read only, since the client cannot write it, right?

**Comment by jsangmeister** [comment]
Yes, I thought about that but wasn't sure what exactly the meaning of `read_only` was. If it is meant only as an indicator for the client, then yes, it has to be set to `read_only`. In the backend this flag is currently not checked.

**Comment by FinnStutzenstein** [comment]
@reiterl please add `read_only: true`, so it can be merged.

**Comment by reiterl** [comment]
Added read_only and description to motion/number_value.

**Pull request merged**
