### PR TITLE
Fixing paragraphs in lists when exporting PDF (fixes #3343)

### LINKED ISSUE #3343: Motion PDF: Wrong indentation if p-tag is used in list elements
* Create a new motion text with some bullet list items.
* Add `<p>` tags arround text in list elements: `<li><p>...</p></li>`. (Note: This is a typical behavior after copy paste list items from Word/LibreOffice into OpenSlides.) 
Looks good in web view:
motion-list-1

* Create pdf of motion. The indendation is broken for each list element block - and there is also an offset between lines and line numbers. See:
motion-list-2

Removing the `<p>..</p>` tags resolved the problem.

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze travis should be fixed

**Comment by emanuelschuetze** [comment]
... and add PR number to CHANGLOG entry (in General > Bugfixes for PDF)

**Comment by emanuelschuetze** [comment]
Travis failed

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Should be ok now, a line was gone while rebasing.

**Pull request merged**
