### PR TITLE
OS4 export

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Export checked with https://github.com/OpenSlides/OpenSlides/pull/6124 (use the `--import` flag): Works!

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze @tsiegleauq Two open questions:
- Where to export: Currently, I've added a new button "Export to OS4" in the legal notice->dev tools which is only accessible for superadmins. It downloads an `export.json`.
- Should I include the actual mediafiles: Currently no file data (blob) is included, so when exporting an instance, no logos/pdfs/... are lost. I can include them, if it is necessary.

**Comment by tsiegleauq** [comment]
> Where to export: Currently, I've added a new button "Export to OS4" in the legal notice->dev tools which is only accessible for superadmins. It downloads an export.json.

I'd put it in the settings dot-menu under the "reset to default" visible for the admin group

**Comment by FinnStutzenstein** [comment]
> I'd put it in the settings dot-menu under the "reset to default" visible for the admin group

Done

I spoke with Emanuel: Blobs shoudlbe included. I'm working on it, but it will be finished thursday.

**Comment by emanuelschuetze** [comment]
First test of os4 export in my local installation runs into error:

```
server_1      | Traceback (most recent call last):
server_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
server_1      |     response = get_response(request)
server_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
server_1      |     response = self.process_exception_by_middleware(e, request)
server_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
server_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1      |     return view_func(*args, **kwargs)
server_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
server_1      |     return self.dispatch(request, *args, **kwargs)
server_1      |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
server_1      |     response = self.handle_exception(exc)
server_1      |   File "/app/openslides/utils/rest_api.py", line 136, in handle_exception
server_1      |     return super().handle_exception(exc)  # type: ignore
server_1      |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
server_1      |     self.raise_uncaught_exception(exc)
server_1      |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
server_1      |     raise exc
server_1      |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
server_1      |     response = handler(request, *args, **kwargs)
server_1      |   File "/app/openslides/utils/views.py", line 32, in method_call
server_1      |     return Response(self.get_context_data())
server_1      |   File "/app/openslides/core/views.py", line 738, in get_context_data
server_1      |     return OS4Exporter().get_data()
server_1      |   File "/app/openslides/core/export.py", line 159, in get_data
server_1      |     self.modify_motion_poll_ids()
server_1      |   File "/app/openslides/core/export.py", line 254, in modify_motion_poll_ids
server_1      |     max([x["id"] for x in self.get_collection("assignments/assignment-poll")])
server_1      | ValueError: max() arg is an empty sequence
```

**Comment by FinnStutzenstein** [comment]
Fixed. I included the mediafile blobs. Tested in the dev setup (mediafiles saved on disc) and prod setup (mediafiles saved in mediafile-database)

**Review by emanuelschuetze — APPROVED** [review]

**Comment by vedagel** [comment]
Hi, where to find this function? At my OS4 Instance there is no button for this at legal notice...
thanks for your help

**Comment by jsangmeister** [comment]
@vedagel this PR implements the export function __in OS3__. See https://github.com/OpenSlides/OpenSlides/issues/6551#issuecomment-1436517783 for how to use it. We currently do not offer an OS4-internal export.

**Pull request merged**
