### PR TITLE
Support http3

### PR DESCRIPTION
**Pull request by ostcar**
@peb-adr I would like to test http3. Caddy 2.6 supports it. Could you install this version on a test service and give me direct access? (without any other proxy in between)

### CODE REVIEW

**Comment by ostcar** [comment]
I opened this branch as a experiment. But I realize now, that the caddy server does not support old versions. So I think we should merge this in any case

**Comment by jsangmeister** [comment]
@ostcar please don't open branches on the main repo, but instead in your own branch.

**Comment by ostcar** [comment]
> @ostcar please don't open branches on the main repo, but instead in your own branch.

Sorry. I have probably misconfigured my local environment. I will fix this, create a new PR and delete this one (with the branch).

**Comment by jsangmeister** [comment]
thanks - same goes for https://github.com/OpenSlides/OpenSlides/pull/6554 btw ;)

**Comment by ostcar** [comment]
I created a new PR that uses an external branch: https://github.com/OpenSlides/OpenSlides/pull/6558

**Pull request closed without merging**
