### PR TITLE
Migrate to angular 9

### PR DESCRIPTION
**Pull request by tsiegleauq**
Migrate OpenSlides to Angular 9

- [x] [ngrid](https://github.com/shlomiassaf/ngrid/issues/79) has still some issues with ivy
- [x] [Angular TinyMCE](https://github.com/tinymce/tinymce-angular/issues/135) still seems to require an update (it works anyways)
- [x] ngx-file-drop also requires angular 8 libraries. Tho there would be alternatives (works anyways)
- [x] The projector is currently not working due to a null injector error
~~[Bazel](https://angular.io/guide/bazel) should be used to speed up the building process. This could require some restructuring.~~

### CODE REVIEW

**Comment by tsiegleauq** [comment]
[ngx-file-drop](https://github.com/georgipeltekov/ngx-file-drop/issues/194) also requires angular 8 libraries. Tho there would be alternatives

**Comment by shlomiassaf** [comment]
@tsiegleauq try version `2.0.0-rc.0` of ngrid, should work with angular 9.0.6 +

**Comment by tsiegleauq** [comment]
90% of OpenSlides is already working fine.
The thing nor working right now it the projector - this still WIP but can be tested.

Angular 9, AOT, Ivy, Postinstall script.

**Comment by tsiegleauq** [comment]
@shlomiassaf in our case, nGrid works absolutely perfect in angular 9 :)

**Comment by FinnStutzenstein** [comment]
@tsiegleauq What is currently not working on the projector?

**Comment by tsiegleauq** [comment]
@FinnStutzenstein basically the slide manager service.
Apparently, JIT compiling the slide components won't work with AOT.

**Comment by FinnStutzenstein** [comment]
Is this PR rebased on master, so that this commit (https://github.com/OpenSlides/OpenSlides/commit/76bd184ff41483d0877b304486d686e5ff1cc43f) is present in this branch?

**Comment by tsiegleauq** [comment]
Yes it's ts. This commit, as well as the whole voting, is already there. You might want to take a look at the projector errors. First build might take a while due to ivy

**Comment by tsiegleauq** [comment]
Bazel for angular currently offers no clear migration path for most projects.
Our sass imports (mainly `~`) are currently tief to WebPack. To adjust bazel building, we would have to keep the configuration files in out project which is discouraged.
I'd recommend to stick with WebPack for now.

**Comment by shlomiassaf** [comment]
@tsiegleauq Glad to hear you are now in angular 9. 

We still didn't migrate, so your project is our front-line battle ground for nGrid.
Please feel free to contact me directly, if any issues arise.

Thanks!

**Comment by tsiegleauq** [comment]
Tested PWA on Local nginx

**Pull request merged**
