### PR TITLE
Add amendment list

### PR DESCRIPTION
**Pull request by tsiegleauq**
- multi select does not really do anything. Should share the same functionality with motions
- filtering by the parent ID from the a motion detail might be a little inconvenient
- sorting by line-number doesn't work yet

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
And please allow to deaktivate the parent-motion-filter if you navigate from motion detail to amendment list (currently you get a new amendment list with x from x amendments; better: show full amendment list and activate the parent filter and show x from y amendments)

**Comment by tsiegleauq** [comment]
> Can you extend easily the search filter that users can seach also in the complete diff part which is shown in the table?

Might be possible, if the diff-part is present in the motion-model itself. Otherwise it might be possible since we reworked the motion and amendment relations. We cannot really search-filter dynamic properties (yet).

> And please allow to deactivate the parent-motion-filter if you navigate from motion detail to amendment list (currently you get a new amendment list with x from x amendments; better: show full amendment list and activate the parent filter and show x from y amendments)

The filter definition is stored in local storage - so is the the mere existence of the parent-motion filter. I would probably need to either not save the filters for amendments, clear them every time or save them in another key for every (parent) motion.

**Comment by emanuelschuetze** [comment]
Ok, let us merge this PR today.
@tsiegleauq Can you give me a hint how can I resolve the travis error (client testing)? Thanks!

**Comment by tsiegleauq** [comment]
ill take a look at it. Shouldnt be too hard

**Pull request merged**
