### PR TITLE
Updated start script help text and custom commands. Fixed #1987.

### LINKED ISSUE #1987: 'openslides start' needs port option
If you install 2.0b4 (`pip install openslides-2.0b4.tar.gz`) you can run OpenSlides server via `openslides start` only. There is no `manage.py runserver` command in release build. The server will run on `0.0.0.0:8000`.

With the start script you can not change host and port. At least changing the port is important for production use (e.g. adminstrators typically wants to change the port to `80`).

See also #1532.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
I tested it:
* short help summary text for `createsettings --help` still missing.
* `openslides --help` contains only `start` and `createsettings` in the list of available subcommands. The list contains all (for OpenSlides relevant) subcommands. Move these subommand from epilog to the list and add a short help text. Here my suggestion:
``` 
$ openslides --help
usage: openslides [-h] [--version] {start,createsettings} ...

Start script for OpenSlides. If it is called without any argument, this will
be treated as if it is called with the 'start' subcommand. That means
OpenSlides will setup default settings and database, start the tornado
webserver, launch the default web browser and open the webinterface.

optional arguments:
  -h, --help            show this help message and exit
  --version             Show version number and exit.

Available subcommands:
  Type 'openslides <subcommand> --help' for help on a specific subcommand.

    start               Setup settings and database, start tornado webserver,
                        launch the default web browser and open the
                        webinterface. The environment variable
                        DJANGO_SETTINGS_MODULE is ignored.
    createsettings      Create the settings file.
    createsuperuser     Creates or resets the admin user.
    backupdb            Backups the SQLite3 database.
    migrate             Updates database schema.
    runserver           Starts the Tornado webserver.

There are some more subcommands available which belong to Django's
command-line utility for administrative tasks. Type 'openslides help' (without
the two hyphen-minus characters) to list them all.
Type 'openslides <subcommand> help' for help on a specific subcommand.
``` 

Question: Is the subcommand `syncdb` still required? Or is this command already included in `migrate`? So, what's required to enter if an user want's to start OpenSlides without `start` command? `createsettings` -> `migrate` -> `runserver`? Anything else?

**Comment by emanuelschuetze** [comment]
I think about if the option `--development` (of `openslides start --development`) has the right wording... It's not really a development feature to keep all settings/database etc. in the same directory and not in .config and .local. So my suggestion: rename this option and improve the help text (`command for development purpose`) which is not really helpful to understand what this option make.

**Comment by normanjaeckel** [comment]
* `python manage.py createsettings --help` prints out some help text. What is missing here?

**Comment by normanjaeckel** [comment]
Syncdb is deprecated. Use only migrate. The workflow is: createsettings, migrate, runserver.

**Comment by normanjaeckel** [comment]
Ready for next review. Renaming `--development` option is another issue you have to open.

**Comment by emanuelschuetze** [comment]
`python manage.py createsettings --help` shows only "usage" and "optional arguments" but no summary help text which describe what the subcommand do (the other subcommands have a summary help)

**Comment by emanuelschuetze** [comment]
Please remove the string `{start, createsettings} You can choose only one subcommand at once`. This is not really helpful and django doesn't do this in it's help.

**Comment by emanuelschuetze** [comment]
For renaming --development option see #2001.

**Comment by emanuelschuetze** [comment]
So, two remarks still open.

**Comment by normanjaeckel** [comment]
Removing the string `{start, createsettings} ...` is possible but there remains an empty line which is build deep inside the argparse lib. So I propose to remove only the first part of the string. The other thing is fixed.

**Comment by emanuelschuetze** [comment]
Ok. One last question: Is it possible to prevent the unattractive linebreaks after the long subcommands `createsettings` and `createsuperuser`? See:

```
Available subcommands:
  Type 'manage.py <subcommand> --help' for help on a specific subcommand.

                   You can choose only one subcommand at once.
    start          Setup settings and database, start tornado webserver,
                   launch the default web browser and open the webinterface.
                   The environment variable DJANGO_SETTINGS_MODULE is ignored.
    createsettings
                   Creates the settings file.
    backupdb       Backups the SQLite3 database.
    createsuperuser
                   Creates or resets the admin user.
    migrate        Updates database schema.
    runserver      Starts the Tornado webserver.
```

If not, please rebase and merge.

**Comment by normanjaeckel** [comment]
I don't know how to change the linebreaks. These things are deeply inside the argparse lib.

**Pull request merged**
