### PR TITLE
Rework on personal notes.

### PR DESCRIPTION
**Pull request by normanjaeckel**
@FinnStutzenstein Ready for client rework. See #3262.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@normanjaeckel I get an error when I try to POST this data: 
```
{"notes":{"motions":{"1":{"note":"note for the motion with id 1","star":true}}}}
```
Error: notes: Not a valid string.

**Comment by normanjaeckel** [comment]
I think the problem is that the serializer field (users/serializers) expect a string instead of a JSONable object. So we have to set the serializer field explicitly. I can do this ...

**Comment by FinnStutzenstein** [comment]
@normanjaeckel This would be nice!

**Comment by normanjaeckel** [comment]
Please test again.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Also rebased.

**Comment by normanjaeckel** [comment]
@emanuelschuetze Ready for test and merge,

**Pull request merged**
