### PR TITLE
Updated German translations and translatable strings

### PR DESCRIPTION
**Pull request by emanuelschuetze**
The extracted translation strings are now available for translations via transifex:
https://www.transifex.com/openslides/openslides/openslides-3x-javascript-template-enpot/

### CODE REVIEW

**Comment by tsiegleauq** [comment]
@emanuelschuetze 
what is missing here?

- [ ] direct PO loader
- [ ] dynamically load a three (or more) language files

**Comment by FinnStutzenstein** [comment]
@tsiegleauq You do not replace the TranslateService we are currently using, are you?

**Comment by tsiegleauq** [comment]
No. Should I? We would simply change the loader (if possible) to directly handle `.po` files instead of json.

**Comment by emanuelschuetze** [comment]
@tsiegleauq All done. Ready to merge. Your mentioned todo are still open. Please move to an other issue.

**Pull request merged**
