### PR TITLE
Fix linebreak on tags (Fixes #2147)

### LINKED ISSUE #2147: linebreaks can occur inside info blocks
The info blocks are not protected against linebreaks. In this example:
info-button-bug
the blocks for the tag "Soziales" is destroyed by a linebreak.

### PR DESCRIPTION
**Pull request by joelmacht**
Change label class to display: inline-block
Add margin-right for spacing
Add myself to AUTHORS

@emanuelschuetze had to reopen because I messed up my fork repo

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@joelmacht Looks better. But please remove also `{{$last ? '' : ', '}}` in motion_detail.html, line 165 to eleminate the annoying comma between tags.

**Comment by emanuelschuetze** [comment]
> in motion_detail.html
Sorry, I mean motion-list.html

**Comment by joelmacht** [comment]
Updated:
Remove commas between tags

**Comment by emanuelschuetze** [comment]
Good. Ready for merge.

**Pull request merged**
