### PR TITLE
One request for each projection. Added some validation for clear_elem…

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
…ents and prune_elemnts

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
After merge: Create an issue for utils/main.py the `#type: ignore`. The origin is the upate of mypy from 0.580 to 0.590.

**Comment by emanuelschuetze** [comment]
@normanjaeckel You can already start with your review.

**Comment by FinnStutzenstein** [comment]
What do you get for a response text?

**Comment by emanuelschuetze** [comment]
http://localhost:8000/rest/core/projector/project/
-> 400 Bad Request
{"detail":"The id \"{'projectorId': 1, 'mode': 'original'}\" has to be int."}

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Yes we may do this. But clean everything up in another PR.

**Pull request merged**
