### PR TITLE
Defined back references (part 1)

### PR DESCRIPTION
**Pull request by normanjaeckel**
I would like to document the (I call them) back references.

E. g. in `models/meeting.py` I want to define the `committee_id` field with a foreign key to a committee. The related name is also given, e. g. `meeting_ids`. This related field will be automatically added to the committee model but I do not want to define it in `models/committee.py`.

So the quest is to find out, which fields a real relation fields and which are back references. Both belong to the interface of course but I would like to build the back references read only of course.

This pull request is only a first draft with some new sorting. Maybe someone can continue here ...

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Two points:
- We should keep consistent in naming: In the client we call these relations "reverse relations". We should adopt this to the server, so we do not have two  wordings for one principle.
- I do not like to have the relations antisymmetric regarding read/write. It is confusing to have both sides of a relation available, but you can only write one. A programmer must know, whch one to write which might not be intuitive. Especially, when this case can be done programatically: Somewhere in the server you define the relation. E.g. there are users and groups, which are related in a M:N fashion with keys user_ids (for groups) and group_ids (for users). With this information, you can handle writes to both sides, because users and groups are exchangeable. Adding an id to user_ids and modifying group_ids is the same as the other way around. This "relation managing" logic has to be implemented once. The same goes for 1:M and 1:1, so in conclusion you have three types of operations on relations. They are equal for for every relation and equal for "reversed relations" (So the term "reverse relation" is is "incorrect" in this case, becuase both sides are equally handled; it is symmetric).
I mean you might have already written the code for e.g. M:N relations, then just use this code for both sides and even generate the code/handlers for the second side (we should not declare this on both sides to reduce errors by programmers)

**Comment by normanjaeckel** [comment]
The term reverse relation is ok for me.

Ok I can try to create some generic logic so that you can write on both sides of a relation, but it would be great if we can get a little bit more structure into the models spec. I will try this maybe next week.

**Comment by FinnStutzenstein** [comment]
Ok, you mean defining relations like for users `group_ids: user[] (references group/user_<meeting>_ids)` so it is clear, which fields are the associated in a relation?

**Comment by normanjaeckel** [comment]
Yes. In some cases the reference is already given. This should be completed, so it is also easier to pick the correct terms for the model code (options `to` and `related_name` I use when defining relational fields).

**Comment by normanjaeckel** [comment]
Additional question: Do we want to enable that fields are writeable if they are used as (so called specific relation) in relational fields with ids inside the field name?

Example:

    motion/meeting_id: meeting[] (references meeting/motion_ids)
    motion/supporter_ids: user[] (references user/support_motion_<meeting_id>_ids: motion[])

In this case if I change meeting_id of the motion from 42 to 538 I do not only have to adapt the relation in meeting collection (delete motion id in respective array of meeting 42 and add it in respective array of meeting 538) but also have to handle the support_motion_42_ids array (remove motion id here) and support_motion_538_ids (add id here).

If you think this is necessary I can try to do it (maybe needs more time) or we just disable this feature (meeting id of motions can not be changed any more).

**Comment by FinnStutzenstein** [comment]
> meeting id of motions can not be changed any more

This is the wanted behavior.

**Comment by normanjaeckel** [comment]
Ok.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Ping

**Comment by normanjaeckel** [comment]
I have to create a new branch and pull request.

**Pull request closed without merging**
