### PR TITLE
Moved custom slides to own app topics. Renamed them to Topic. Fixed #…

### PR DESCRIPTION
**Pull request by normanjaeckel**
…2402.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Migration test looked good. Ready for merge.

**Comment by emanuelschuetze** [comment]
I tested your branch and I get a JS error if you check the 'done' checkbox in agenda list view:
```
angular.js:13920 TypeError: Cannot create property 'quickEdit' on number '1'
    at Agenda.save.then.message (site.js:152)
```

**Comment by emanuelschuetze** [comment]
Migrations works good for customslides -> topics.

So one remark (bug). Then ready for merge.

**Comment by emanuelschuetze** [comment]
BTW: Let us try to use the new wording "topic" in the UI.

**Comment by normanjaeckel** [comment]
Ready for merge.

**Comment by emanuelschuetze** [comment]
Ok,  'done' checkbox in agenda list view works no without errors. Wait for travis. Then merge...

**Comment by matakuka** [comment]
travic-ci seems to be stuck (may be a server issue, i had triple test times earlier this day)

**Comment by emanuelschuetze** [comment]
Travis rebuild and finished succussfully after close and reopen this pull request.

**Pull request merged**
