### PR TITLE
Change user import table

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@emanuelschuetze Do you want to have an extra column (the first) with the checkboxes? And do we need a checkbox (de-)select all (like in all other tables)?

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
> Do you want to have an extra column (the first) with the checkboxes? 

No, I want to click on the black check-circle-icon to select/unselect the row. Then the icon (and the counter) should change.

> And do we need a checkbox (de-)select all (like in all other tables)?

No, not necessary.

**Comment by emanuelschuetze** [comment]
Overflow scrolling successfully tested. Still open: select/deselect rows.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Ready to test.

**Comment by emanuelschuetze** [comment]
> What is the difference to the old behaviour?

If fixes #2667 and makes some minor improvements for preview table.

> Do we need a CHANGLOG entry?

No. So ready for merge...

**Pull request merged**
