### PR TITLE
Add line numbers to pdf (fixes #2300)

### LINKED ISSUE #2300: Line numbers in PDF for Motions
by @ThomasJunk from #2288

> Line numbering is not implemented

Line numbers have been intruduced in #2292 and need to be in the PDF as well.
According to what I saw all the required information are in the plain HTML code, so if line numbers are activated in a motion the PDF shall be generated with containing line numbers.

Superscript and Subscript numbers are currently not possible with pdfmake [https://github.com/bpampuch/pdfmake/issues/36](url)

### PR DESCRIPTION
**Pull request by tsiegleauq**
Adds "inline like" line numbers to PDF if line numberins was selected.
Currently I support inline-style only, adding a column for outside-style requires quite some changes I guess.

Example:
[Antrag 3-example.pdf](https://github.com/OpenSlides/OpenSlides/files/463895/Antrag.3-example.pdf)

@emanuelschuetze

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
You implement the outside mode of line numbering. Good! But we need also the inline mode in this pull request.
Wish for the current outside mode: Please use a clear left-justified for the text (e.g. use a fix with for line number "column"). And please add a bit more space between numbers and text.

Please hide title "reason" if no reason is available for this motion.

**Comment by tsiegleauq** [comment]
@emanuelschuetze
I implemented inline, not outline. outline requires adding columns. this requires a lot of changes

**Comment by emanuelschuetze** [comment]
You implemented a "inline" form of outside mode ;-). The real "inline" mode is still missing.

**Comment by tsiegleauq** [comment]
I honestly do not know what you mean with that. We have a smaller number in
the beginning of the line. without a column or any bigger space.
According to my understanding of the line number features this is inline.
outline would be a bigger number in an own column

Am 09.09.2016 15:42 schrieb "Emanuel Schütze" <notifications@github.com>:

**Comment by tsiegleauq** [comment]
I made the according changes and added both outside and inline line numbers.
The current implementation uses the same information as the original layout.

I give some examples below:

[example-Nothing.pdf](https://github.com/OpenSlides/OpenSlides/files/475364/example-Nothing.pdf)
[example-Inline.pdf](https://github.com/OpenSlides/OpenSlides/files/475365/example-Inline.pdf)
[exmaple-Outline.pdf](https://github.com/OpenSlides/OpenSlides/files/475366/exmaple-Outline.pdf)

@emanuelschuetze @normanjaeckel 
please review this soon. Thanks!

**Comment by emanuelschuetze** [comment]
Examples looks nice! I'll make a test.

**Comment by tsiegleauq** [comment]
You should elaborate more on these two points. I dont know what you mean by that.

> Use a "real" paragraph with more space (top/bottom margin) - like in motion-detail.html.
> Add space between "As of" and "" in pdf header.

**Comment by emanuelschuetze** [comment]
Here an example to show what I mean with "paragraphe with more space" :

Current situation in pdf output:
```
1  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
2  sed do eiusmod tempor incididunt ut labore et dolore.
3  magna aliqua. Ut enim ad minim veniam, quis nostrud
4  exercitation ullamco laboris nisi ut aliquip ex ea commodo.
```

Expected situation in pdf output:
```
1  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
2  sed do eiusmod tempor incididunt ut labore et dolore.

3  magna aliqua. Ut enim ad minim veniam, quis nostrud
4  exercitation ullamco laboris nisi ut aliquip ex ea commodo.
```

Summary:
After a  `<p>...</p>` block you should a vertical space before the next blocks begins. An user should see paragraphs in pdf output. Currently there is a whole long text. Ok?

**Comment by tsiegleauq** [comment]
I made the according changes. Please see the examples below and review soon @emanuelschuetze @normanjaeckel 

[Motion-3-No-Line-Numbers-No-Reason-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482092/Motion-3-No-Line-Numbers-No-Reason-Paragraph.pdf)
[Motion-3-Inline-Line-Numbers-No-Reason-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482093/Motion-3-Inline-Line-Numbers-No-Reason-Paragraph.pdf)
[Motion-3-Outside-Line-Numbers-No-Reason-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482094/Motion-3-Outside-Line-Numbers-No-Reason-Paragraph.pdf)
[Motion-3-No-Line-Numbers-with-Reason-without-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482096/Motion-3-No-Line-Numbers-with-Reason-without-Paragraph.pdf)
[Motion-3-Inline-Line-Numbers-with-Reason-without-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482097/Motion-3-Inline-Line-Numbers-with-Reason-without-Paragraph.pdf)
[Motion-3-Outside-Line-Numbers-with-Reason-without-Paragraph.pdf](https://github.com/OpenSlides/OpenSlides/files/482098/Motion-3-Outside-Line-Numbers-with-Reason-without-Paragraph.pdf)

**Comment by emanuelschuetze** [comment]
All done. @normanjaeckel Ready for your review and merge (asap).

**Pull request merged**
