### PR TITLE
motion projection mode is optional and sensitive for the config

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@CatoTH Can you plug-in the logic required by `getSlide()`?

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@CatoTH @emanuelschuetze I added CRs as a dependency to motions -> in view motions one can now access CRs (Tobias: is this helpful for you in some other cases?)

**Comment by CatoTH** [comment]
@FinnStutzenstein Would the same be possible with the amendments to a motion? In that case, querying these in the motion detail view could be solved slightly more elegant...

**Comment by emanuelschuetze** [comment]
This PR already works for amendments because an amendment has no CRs. Thr mode buttons are hide.

**Comment by CatoTH** [comment]
From my understanding, a motion that has amendments, but no CRs, should still have the buttons (contrary to a motion without none at all). For that, having the amendments in the ViewMotion would be necessary.

**Pull request merged**
