### PR TITLE
New autoupdate format

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by ostcar** [comment]
The old format is currently used be the projector code. This the projector code still uses the CollectionElement, it is not so easy to fix. So I want to keep the old code for the projector until a decision is made, if the projector is rewritten for 3.0

**Comment by ostcar** [comment]
I don't understand why travis fails. @normanjaeckel do you know how to fix it? It seems, the python 3.6 code uses the config file from another commit

**Comment by FinnStutzenstein** [comment]
@ostcar Travis is ok now

**Comment by FinnStutzenstein** [comment]
I added a commit for the new client.

**Comment by emanuelschuetze** [comment]
@ostcar Any work open here? Or should we review/merge?

**Comment by ostcar** [comment]
You can review/merge this

**Comment by FinnStutzenstein** [comment]
I'll push my commit on top of yours tomorrow. Could be merged then, right?

**Comment by ostcar** [comment]
If someone approve this, I merge it. I hope someone approves this before tomorrow evening.

**Comment by FinnStutzenstein** [comment]
I'll do this tomorrow morning

**Pull request merged**
