### PR TITLE
list of speakers overlay (fixes #2211)

### LINKED ISSUE #2211: New list of speakers overlay
The current list of speakers (of projected agenda item) should be shown on the projector in a new "overlay" - a box on the bottom right corner of the projector slide. See https://docs.openslides.org/de/_images/Agenda_04.png for an example in OpenSlides 1.7. (This feature is still missing in 2.0.)

The overlay should show the last speaker (in grey), the current speaker (in bold) and the next max. 5 speakers. The overlay should be hide/transparent if the list of speaker is empty or no list of speakers is available for the current slide (e.g. if you project an participant).

To show/hide this overlay add a new section 'List of speakers' to the projector sidebar (maximize it by clicking on projector button on the right side of the webinterface view). There place the new section below countdowns and messages. In the new section should be a project button to enable/disable the overlay on projector - similar like for countdown or messages.

**Optional:**
Add the two control buttons ("Begin next speach" / "End next speach") from list of speakers control view (agenda/item-detail.html) to the overlay control section (below the show/hide projector button). Then an administrator can control the main functions of a list of speakers from projector sidebar (enable/disable, start/stop).

### PR DESCRIPTION
**Pull request by matakuka**
This is a different approach from #2241, touching the same issue #2211. 
- it does not create a projector element, just a projector variable "speakeroverlay: true|false"
- the overlay gets the permissions the slide gets. So permission granting issues are avoided.

- only remaining issue from my view: if not user_can_see_names, name lists will be empty.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Thanks for this approach. I am not so happy with implementing non generic features directly into the projector model. I can see some advantages but I do not think they are worth breaking up our (maybe only my) current idea of what the projector is and what the projector elements are.

The permission problem is not completly solved. We have to add (or simply check) permissions to see agenda items to all object (motion, assignment, customslide) slides. Then everybody can see the list of speakers of a motion if this motion is displayed on the projector even if the list of speakers flag is set to False.

What about a more or less lazy reloading of DS objects by the active slide controller if something changes?

In case of MotionSlideCtrl
```javascript
$scope.$watch(function () {
  return Agenda.lastModified() + Motion.lastModified() + Category.lastModified() + User.lastModified() + ...;
}, function () {
    // Now just find, findAll and/or loadReleations of what is necessary here.
});
```

**Comment by matakuka** [comment]
Done without the issues discussed in #2302.

The permission for the agenda_item is already there. 

The problem lies in that agenda_item needs to load a relation, too (agenda_item.user), and thus we need permissions for Users (whom, we don't know on page load, as it changes).

**Comment by matakuka** [comment]
see also #2321, where the issue for the user names will be solved (will need some minor rework in this PR)

**Comment by normanjaeckel** [comment]
My objection is still valid. See above.

@ostcar Some opinion?

**Comment by ostcar** [comment]
I don't understand the question.

**Comment by matakuka** [comment]
@normanjaeckel I need help resolving.

For this (or #2241) I cannot get resolve to work, and I am lost.
- Is a resolve for a single new slide via slidesProvider possible?
- For a resolve upon (re-) loading the projector, it does not seem to work. Probably I am doing it wrong.
As I understand, it is 
(core/site.js)
```
.state('projector', {
                url: '/projector',
                templateUrl: 'static/templates/projector-container.html',
                data: {extern: true},
                onEnter: function($window) {
                    $window.location.href = this.url;
                },
                resolve: {
                    motions: function(Motion) {
                        return Motion.findAll().then(function(motions) {
                            angular.forEach(motions, function(motion) {
                                Motion.loadRelations(motion, 'agenda_item');
                            });
                        });
                    },
                })
```
Then, in the ProjectorCtrl/ProjectorContainerCtrl:
```
.controller('ProjectorCtrl', [
    'motions',
    function(motions) {
    do_something(motions);
 }
```
However, motions is not injected there (core/projector.js):

```
"Error: [$injector:unpr] Unknown provider: motionsProvider <- motions <- ProjectorContainerCtrl
```

**Comment by normanjaeckel** [comment]
You can not use a resolve in site.js to get some vars to the projector.js because these are two different angular apps. The state definition in site.js is only a redirect, see onEnter ... window.location .... There the browser reloads the projector page one time.

To use something like resolve in the slidesProvider is not implemented yet. This would be nice.
Nevertheless I think we should follow either my approach in #2357 or a new proposal of @ostcar. We will discuss this in about 10 days. Before it is not worth doing anything here. But feel free ...

**Comment by normanjaeckel** [comment]
New approach in #2371 .

**Pull request closed without merging**
