### PR TITLE
Update Datastore interface

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Review by jsangmeister — APPROVED** [review]

**Comment by normanjaeckel** [comment]
Maybe add some explaination ... ;-)

**Comment by jsangmeister** [comment]
Take a look at the mentioning issues :)

**Comment by normanjaeckel** [comment]
Ok, but a short description for CollectionFieldLock is still missing in this file.

**Comment by jsangmeister** [comment]
> Ok, but a short description for CollectionFieldLock is still missing in this file.

Yes, will add it.

**Comment by jsangmeister** [comment]
Added the filter part in https://github.com/OpenSlides/openslides-datastore-service/pull/109. Changed `max_position` to `position` to keep it uniform with the other return values.

**Comment by FinnStutzenstein** [comment]
> Changed max_position to position to keep it uniform with the other return values.

The change isn't pushed, is it?

**Comment by jsangmeister** [comment]
> > Changed max_position to position to keep it uniform with the other return values.
> 
> The change isn't pushed, is it?

No, not in this PR, I only changed it in https://github.com/OpenSlides/openslides-datastore-service/pull/109

**Comment by FinnStutzenstein** [comment]
@jsangmeister I think it can be merged since it is implemented.

**Comment by jsangmeister** [comment]
> @jsangmeister I think it can be merged since it is implemented.

Added docs and renamed position. If you want you can merge it.

**Pull request merged**
