### PR TITLE
Update labels and milestones script

### PR DESCRIPTION
**Pull request by jsangmeister**
- simplified script
- milestones: removed `4.1` and added `4.3`

### CODE REVIEW

**Review by rrenkert — COMMENTED** [review]
Looks good so far.

Should we move scripts that run locally and not on gh itself to a `dev/gh-scripts`or something?

**Comment by jsangmeister** [comment]
> Should we move scripts that run locally and not on gh itself to a `dev/gh-scripts`or something?

Sure, I'm open to that. But I think `dev/scripts/` suffices if we want to move it out of the `.github` folder, I don't think a separate `gh-scripts` folder is neccessary.

**Comment by rrenkert** [comment]
`dev/scripts` is ok for me.

**Comment by jsangmeister** [comment]
done

**Pull request merged**
