### PR TITLE
Add backend setup

### PR DESCRIPTION
**Pull request by jsangmeister**

### CODE REVIEW

**Comment by jsangmeister** [comment]
I don't think this is finished, I will take a look next week

**Comment by emanuelschuetze** [comment]
Ok, then we have to move it to 4.1 milestone.

**Comment by jsangmeister** [comment]
Related PRs to unify the naming etc.:
https://github.com/OpenSlides/openslides-backend/pull/1489
https://github.com/OpenSlides/openslides-auth-service/pull/135
https://github.com/OpenSlides/openslides-datastore-service/pull/221
https://github.com/OpenSlides/openslides-media-service/pull/56
https://github.com/OpenSlides/openslides-media-service/pull/57

**Comment by jsangmeister** [comment]
Added commands to automatically switch contexts between `dev` and `test` (see deve docs for more details). This was the easiest solution I could come up with, since all containers depend on the postgres db and it is not easily possible to host multiple databases in one postgres container or replace it while it is running. I'm open for feedback @r-peschke @rrenkert and whoever is interested

**Review by rrenkert — APPROVED** [review]

**Review by r-peschke — APPROVED** [review]
Good to have a base like this

**Pull request merged**
