### PR TITLE
Fix initial data

### LINKED ISSUE #5826: Validate the example data
Finish validating the `docs/example-data.json` with the `docs/models.yml`. This is the first try by Norman: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/modelsvalidator/check_json.py

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
resolves #5826

### CODE REVIEW

**Comment by reiterl** [comment]
Merged into my branch:
find the following errors still:

Check for ../../docker/initial-data.json failed:
Type error meeting 1: field export_pdf_fontsize is not number
RelationError: meeting/motion_poll_default_group_ids/1: 5 not in [6]
RelationError: meeting/assignment_poll_default_group_ids/1: 5 not in [6]
RelationError: meeting/poll_default_group_ids/1: 5 not in [6]
RelationError: meeting/motion_state_ids/1: 1 not in []
RelationError: meeting/motion_state_ids/1: 2 not in []
RelationError: meeting/motion_state_ids/1: 3 not in []
RelationError: meeting/motion_state_ids/1: 4 not in []

**Review by reiterl — CHANGES_REQUESTED** [review]
Still some errors are still there.

**Comment by FinnStutzenstein** [comment]
Thanks, I fixed the reported issues.

**Review by reiterl — APPROVED** [review]
Check with the new checker passes.

**Comment by FinnStutzenstein** [comment]
Ok, I'll merge for now.

**Pull request merged**
