### PR TITLE
New template design

### PR DESCRIPTION
**Pull request by emanuelschuetze**
- Great thanks to Jörn Bensch (from triagonale.de) for new base  template!
- A lot of adaptations in all templates for new design.

### CODE REVIEW

**Comment by ostcar** [comment]
@normanjaeckel I can not review this big pr today. Can you do it?

**Comment by normanjaeckel** [comment]
Some remarks:
* Check images, remove old and unused files, rename logo files.
* Check webfont package, use a more established source or (min.) open an issue that we think about this before the next release.
* Open issue for more verbose "isFilter" var name.

**Comment by emanuelschuetze** [comment]
@normanjaeckel see review commit

**Comment by emanuelschuetze** [comment]
split out 2 issues: see #1726 and #1728

**Comment by normanjaeckel** [comment]
Ok, rebase and merge.

**Comment by emanuelschuetze** [comment]
Done. ready to merge.

**Pull request merged**
