### PR TITLE
Drag-and-drop files upload

### PR DESCRIPTION
**Pull request by serge1peshcoff**
I've implemented some basics of drag-and-drop for files upload in "Files" tab.
I've decided that implementing this in a way that opens up a form with the "newFile" field already filled in is too complicated, so I've decided to implement it the other way: when the user drops the file onto the drop area, it is uploaded automatically with the 'name' field set as the filename and the 'uploader' field set as the current user.

NOTE: this PR is not for merging yet, it's mostly WIP, as I've implemented some basic stuff and there's a lot of things to be done before merging, for now it's just to show the idea of what I'm going to do.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
See #3510.

**Comment by normanjaeckel** [comment]
When this PR is finished later please do not forget to add a line to AUTHORS file.

**Comment by serge1peshcoff** [comment]
Sooo, I've implemented it finally, check this out. (It's not a final version though, see below.)

Two concerns before this is finalized:
1) I am not that good at CSS, can somebody help me improving the UX/UI of the dropzone?
2) I want to add another Config setting to set the default 'hidden' attribute for the files uploaded via dropzone, so the user would have the ability to upload hidden files by default. How can I add another Config option?

Thanks in advance.
@normanjaeckel @emanuelschuetze @FinnStutzenstein

**Comment by FinnStutzenstein** [comment]
Hi, I would prefer to implement the dropzone into the `+new` dialog. See [this example](http://nervgh.github.io/pages/angular-file-upload/examples/simple/). Maybe adding a queue for all selected files, so the user can set the name and hidden flag for each file.
You can also mark the file-choose-field as a dropzone, too: The user can choose, if he wants to select files of drop them there. (File: core/static/templates/core/file.html)

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein AFAIK you can already drop the files to `Upload` button on the `New` dialog and that would work just as you described. I can do this also, but this would mean doing extra steps for the user, and my approach intends to save clicks and extra steps for the user.

Can you please describe the upload workflow you are thinking about? I was thinking about the following:
1) User opens the `Files` tab
2) User drops the file onto the dropzone
3) The `hidden` attribute of the mediafile-to-upload is set to either true or false, depends on the config.
4) The file is uploaded successfully/an error is displayed.

Also I was thinking about hiding the dropzone and displaying it only if the user is dragging something onto the browser window, but it should be a little bit harder to implement. What do you thing about?

**Comment by emanuelschuetze** [comment]
@serge1peshcoff We discussed and tested your pull request. We don't like the drag&drop area in the mediafile list view - sorry, but it looks not very nice...
Suggestion: Please provide a multi select file chooser which can upload multiple selected files at once. Optional: you can add a preview table in create form of all selected files...

**Comment by emanuelschuetze** [comment]
@serge1peshcoff What do you think about my suggestion (multi select file chooser)? Can you implement it in your pull request? Then we could merge it for 2.2.

**Comment by serge1peshcoff** [comment]
@emanuelschuetze looks cool, but I don't have that much time lately unfortunately so I don't have time working on that :(
I'll try to get back on that when I can though.

**Comment by emanuelschuetze** [comment]
Closed - see new pull request #3650

**Pull request closed without merging**
