### PR TITLE
Error messages and global messaging service (closes #2949)

### LINKED ISSUE #2949: Nicer error messages, if the server is down
For example: 

1. Start openslides
2. login as admin
3. go to the "overlay" to cretae a new user.
4. stop openslides
5. click on save.

Only a red par appears with no text at all

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@emanuelschuetze As I proposed to you: Whats about removing all alerts in forms, list views etc. and use the messaging service? (You can test this easily to make your opinion; just include something like `Messaging.addMessage(text, 'error')` to an error handler)

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Projector shows error: `Unknown provider: ErrorMessageProvider <- ErrorMessage <- autoupdate`

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze All fixed.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I replaced all left .success and .error's.

**Comment by normanjaeckel** [comment]
Please merge if there were no more changes.

**Comment by emanuelschuetze** [comment]
@normanjaeckel sorry, only minor changes by @FinnStutzenstein  which he rebased directly. I'll merge ...

**Pull request merged**
