### PR TITLE
Show latest meaningful poll results in autopilot

### PR DESCRIPTION
**Pull request by tsiegleauq**
Shows the latest meaningful poll result in autopilot
The last published poll result from the corresponding content object

### CODE REVIEW

**Comment by tsiegleauq** [comment]
@emanuelschuetze fixed the errors. Can be tested, needs cleanup.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Works good. But we need the pie/donut chart for motion polls!

**Comment by tsiegleauq** [comment]
- restructured and refactored how and when charts are drawn
 - improved performance of cinema and chart drawing
 - unknown resize issues in charts JS that occures in autopilot when the cart was redrawn, cannot be altered using CSS for unkown reasons

**Comment by tsiegleauq** [comment]
ping @emanuelschuetze

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Retested:
- show empty mat-card for normal user on autopilot if poll is unpublished (show message "Counting of votes is in progress ..." as in motion-detail view)

Rest looks good!

**Comment by tsiegleauq** [comment]
restructured `*-poll-detail-content-component` to be more transparent about it's current status and behavior for autopilot, projector, poll-view and poll-detail-view and all four states.

this change is heavy, test with care.

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Retested: If the second poll of a motion or assignment is running the result of the last (first) poll is still visible in AP. Please hide last poll if a next poll is started.

**Comment by emanuelschuetze** [comment]
Retested:
Project a (motion) poll. Go to autopilot. 
=> The projector is empty!

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
