### PR TITLE
category prefix is currently optional

### PR DESCRIPTION
**Pull request by MaximilianKrambach**
on server side a category prefix is optional. This PR acknowledges that and displays categories accordingly

### CODE REVIEW

**Comment by MaximilianKrambach** [comment]
pdf is changed too, now

**Comment by emanuelschuetze** [comment]
prefix check still missing for motion catalog pdf -> table of content.

**Comment by MaximilianKrambach** [comment]
it's a moving target. That one wasn't there this morning.... fixed

**Comment by MaximilianKrambach** [comment]
done @emanuelschuetze

**Pull request merged**
