### PR TITLE
Update .gitignore to exclude .env from repository

### PR DESCRIPTION
**Pull request by topelrapha**

### CODE REVIEW

**Comment by tsiegleauq** [comment]
why remove secrets?

**Comment by topelrapha** [comment]
Because the .env file isn't in secrets folder 

⁣Gesendet mit BlueMail ​

**Comment by FinnStutzenstein** [comment]
Which `*.env` files are you trying to ignore?

**Comment by topelrapha** [comment]
I have reviewed and reflect my change - you are right. It makes no sense!

**Pull request closed without merging**
