### PR TITLE
Simplified installing of JS and CSS libs. Fixed #1906.

### LINKED ISSUE #1906: Find an other solution for openslides-libs.worker.js
Remove ` <script src="static/js/openslides-libs.worker.js"></script>` from projector.html.

It is not best practice to add extra libs and generate extra requests for this. Maybe we can concat this file together with openslides-libs.js.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
I tested your branch. There are some problems:
1. the gulp tasks 'js-libs', 'fonts-libs' and 'ckeditor' runs very long! (>3min). see:

```
[14:03:20] Using gulpfile ~/projects/openslides/src/OpenSlides/gulpfile.js
[14:03:20] Starting 'js-libs'...
[14:03:20] Starting 'css-libs'...
[14:03:20] Starting 'fonts-libs'...
[14:03:20] Starting 'ckeditor'...
[14:03:20] Starting 'translations'...
[14:03:23] Finished 'translations' after 3.78 s
[14:03:23] Finished 'css-libs' after 3.85 s
[14:06:36] Finished 'js-libs' after 3.27 min
[14:06:36] Finished 'fonts-libs' after 3.27 min
[14:06:37] Finished 'ckeditor' after 3.27 min
[14:06:37] Starting 'default'...
[14:06:37] Finished 'default' after 7.3 μs
```

2. The two fonts (Roboto and Open Sans) are not installed correctly. You can't use it in template.

Please test it!

**Comment by emanuelschuetze** [comment]
Problem 1 seems to be already in master (if you run gulp --production). Please check it.

**Comment by emanuelschuetze** [comment]
Both (1+2) seems to be a problem only with 'gulp --production'. The font definition seems to be broken after minifized css code.

**Comment by normanjaeckel** [comment]
Both problems are in current master, so this has nothing to do with this pull request.

**Comment by emanuelschuetze** [comment]
ok

**Comment by normanjaeckel** [comment]
New issue created: #1955.

**Pull request merged**
