### PR TITLE
change all isProjected functions (closes #2462)

### LINKED ISSUE #2462: isProjected should return a list of projector ids
Split out from #2379 for later rework (wait untile #2379 is merged):
The function `isProjected` (in core/base.js and maybe in other apps which override this function) should return a list of all projector ids which project the requested object. This is important for future if OpenSlides UI supports to project an object to multiple projectors.

Example:
The motion 42 is projected on projector 1, 2 and 4. `motion.isProjected()` should return `[1,2,4]`. The projector button consider this list (and show the default button and/or split button blue and select the ul list elements of the projector 1,2 and 4).

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
One thing: To check if a model is projected I have to write `_.indexOf(model.isProjected(), projector.id) > -1` in the projectorbutton template. But lodash is not available in the scopes in the templates. For this reason I put the function `inArray(array, value)` in the root scope.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I cannot reproduce this. Tested with one projector and two projectors. Can you give me the line and instructions how to reproduce, if this is still a problem?

**Comment by emanuelschuetze** [comment]
How to reproduce:
* Start with fresh db. Make sure you run gulp watch.
* open projector sidebar > list of speakers
* click project button of list of speakers overlay

=> JS error `Error: "id" must be a string or a number!` (in angular.js)

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze ping.

**Comment by FinnStutzenstein** [comment]
Todo: fix all project() functions. --> wip state

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze ready for review.

Note: If PR #2529 is merged erlier, this needs some changes.

**Comment by emanuelschuetze** [comment]
Ok, successfully tested.

**Comment by emanuelschuetze** [comment]
Sorry, the 4 commits were not rebased...

**Pull request merged**
