### PR TITLE
Line break algorithm should not be distracted by newline characters

### PR DESCRIPTION
**Pull request by CatoTH**
First part of the bugfix for #3409 - fixes the diff and line breaking algorithms to handle newlines in the database correctly.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@CatoTH How can I test your fix successfully? I tested the following use case:
* Create a motion with long dummy text.
* Activate inilne editing for motion text and added a linebreak by Shift+Enter in first line.
* Add a change recommendation for (new) first line (add a new word in the middle of the line).
* Show diff version: The whole first line is marked deleted+inserted (paragraph diff mode).
Expected behavior: Only the added word should show in insert (inline) mode.

**Comment by CatoTH** [comment]
@emanuelschuetze I suppose, that was yet another edge case...
What I described, was actually even more of a problem, as entering a newline via Shift+Enter was not necessary to produce this problem. Simply editing and saving did add newline characters at the places where the line numbers are in the markup.
I added another fix to the problem with the added BR.

**Comment by FinnStutzenstein** [comment]
How can I test this PR?

**Comment by CatoTH** [comment]
- Create a motion with a long text
- Inline edit, just make a very little change and save
- BUG: At this point, maybe already the line numbering has changed. In the database, you should see newlines in the database.
- If you make a change recommendation for one line, adding one word in the middle, another bug occurrs: another word is marked as changed (deleted / added), as the newline character is recognized as a change.

Both bugs should be fixed in this branch.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please review later. Thanks.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
