### PR TITLE
Refined models

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Note: I renamed motion/identifier to motion/number to avoid further misunderstandings between id and identifier. The name was too ambiguous.

**Comment by normanjaeckel** [comment]
Can you put the models into some kind of ordering (maybe according to old "apps") and also add an empty line between every model. It would be easier to read the file then ...

I propose the following (pseudo-hierarchical) order:

organisation
user
committee
meeting
group
topic
motion
assignment
agenda
projector

and all other models in between.

No problem if you have no time for this. I can do it (but only if I have the time ... :-))

**Comment by FinnStutzenstein** [comment]
OK, will be done later in this week (currently I'm creating example data in this order ;) )

**Comment by FinnStutzenstein** [comment]
Faster than expected: Done :)

**Comment by normanjaeckel** [comment]
Ok. This is very helpful. I looked a bit around and it looked okay for now. I did not check every single line but I think it would be no problem if we want to rename two or three fields later.

Am I right that we do not want to speak about models here but about collections?

**Comment by FinnStutzenstein** [comment]
Your additions are correct! I'll merge this now.

**Pull request merged**
