### PR TITLE
Added display_name to agenda item content object serializer field. Se…

### PR DESCRIPTION
**Pull request by normanjaeckel**
…e #1692.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Ok. Please fix travis and merge asap so that I can use it in my pull request. Thanks.

**Comment by ostcar** [comment]
I don't like this solution. The RelatedItemRelatedField should only contain the information needed to get another object. Each information containing this object can be get from the object. For example use the attribute agendaSupplement from the DS-Model. (We have to remove the bracelets.) Or add another string to the DS-Model or send it with the related object.

This is important, because we could use this field in other cases, too. This field is useful for each generic relation not only agenda items.

**Comment by normanjaeckel** [comment]
@emanuelschuetze Please let us know whether to close this pull request.

**Comment by emanuelschuetze** [comment]
Yes we can close this pull request and should discuss it later.

**Pull request closed without merging**
