### PR TITLE
enables pdf image scaling for CKEditor

### PR DESCRIPTION
**Pull request by tsiegleauq**
Since we cannot use the usuall `.clientWidth` / `.clientHeight` methode, images only get scaled if the user adds custom scale.
If the user does not do anything, we try to process the image in its original scale.

That also means, we will not catch images that are too big.
(also see the issue to this)

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please test and review it. Also travis failed.

**Comment by tsiegleauq** [comment]
> What do you mean with .clientWidth and .clientHeight?

https://developer.mozilla.org/de/docs/Web/API/Element/clientWidth
You can ask objects in DOM what size they do have using .clientHeight. Worked in the past, does not work anymore. Maybe because of web workes or something?

> I propose to save the original image size into the images dict.

How to access this? We usually only can ask images.`<url>` to get base64. Is there a way to get the size directly?

> scale the image, if the original size is above the maximum

Finding out the original size is exactly the problem, since we can only access the base64 and the URL in the image object and `.clientHeight` does not work (anymore).

> But there I would like to have a locked scaling; so if you change x by 10%, y also should change by 10%.

Did you read the code?
```
if (width > maxResolution.width) {
    var scaleByWidth = maxResolution.width/width;
    width *= scaleByWidth;
    height *= scaleByWidth;
}
if (height > maxResolution.height) {
    var scaleByHeight = maxResolution.height/height;
    width *= scaleByHeight;
    height *= scaleByHeight;
}
```

try that: `console.log( element.clientWidth );` a image object in motion and on your local Webserver.

**Comment by FinnStutzenstein** [comment]
Just return not only the dataUrl, but also the width and height [here](https://github.com/tsiegleauq/OpenSlides/blob/6d0f6ebb7fe14fe4bec43611370cbab30d7ce835/openslides/core/static/js/core/pdf.js#L102):
```
resolve({
    data: dataUrl,
    width: img.width,
    height: img.height,
});
```
In this `onload` function, the image width and height are known.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein 
That helped a lot!
I added the changes, rebased and pushed again.
Please review and test again.

If you find the max image dimensions too big feel free to commit changes.

**Pull request merged**
