### PR TITLE
Models to yml

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
@ostcar Please check.

**Comment by ostcar** [comment]
Looks good.

**Comment by normanjaeckel** [comment]
I will try to get some generated code for backend. If this works this PR can be merged.

**Comment by normanjaeckel** [comment]
@FinnStutzenstein Please merge this pull request if everything is ok. We can later remove the old models.txt and also the respective GitHub actions check. @ostcar wrote a validator that checks some cases of syntax and structure.

In https://github.com/OpenSlides/openslides-backend/pull/153 I use this new models.yml to generate a full models.py with all fields.

**Comment by FinnStutzenstein** [comment]
This looks good. One proposal: Can we move the validator into this repo? Than we have everything docs-related at one place.

**Comment by ostcar** [comment]
@FinnStutzenstein I would like to have the validator in a separate repo. The reason is, that I want to reuse the code. I want to import it in the autoupdate-restricter package to get the related-list fields (see https://github.com/OpenSlides/openslides-autoupdate-service/pull/102).

Maybe you can also reuse the code for the permission service?

I am not 100% against moving in to this repo, but I will change the code in the next time and will add more features that are not required for the validation.

**Comment by FinnStutzenstein** [comment]
> but I will change the code in the next time and will add more features that are not required for the validation.

Split it up there than. Move validation related code here and leave the base code in the external repository. But if you need this PR merged, we can do it first.

**Comment by normanjaeckel** [comment]
I would like to merge this PR because I can use the URL in backend repo then. Please discuss what to to with the validator in extra issue.

**Pull request merged**
