### PR TITLE
Always include CRs in motion slide

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by tsiegleauq** [comment]
implemented client, rebased, aligned python code, fixed the python tests,

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
I can't see CRs on motiion slide.

**Comment by tsiegleauq** [comment]
- create motion
- create paragraph based amendment with one line alteration
- in amendment, alter the same line
- project amendment in diff version

**Comment by emanuelschuetze** [comment]
Please try:
* Create motion with text "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa."
* Create amendment (for 1. paragraph): Add "TEST" as first word.
* Create CR for first line and add "END" as last word of this line.
* Project amendment in diff view => "TEST" is visible in green (OK) but "END" is not visible!

**Comment by emanuelschuetze** [comment]
I have to merge it now.
@tsiegleauq Let us fix this next week.

**Pull request merged**
