### PR TITLE
New file upload form (fixes #3510, fixed #3082)

### LINKED ISSUE #3082: ugly button layout in upload file window
- go to the Files menu and try to upload a file

result: 
localhost 8000 2017-03-13 00-22-03

The "Durchsuchen" button is displaced.

### LINKED ISSUE #3510: Drag-and-drop file upload
Hello there.
I am the IT responsible of one big event (800+ people), where we are using OpenSlides to display presentations/videos on stage and on the Internet. And sometimes we need to upload a lot of files to the OpenSlides in a short time, and it takes a lot of time to fill all the values into the upload form, find the file in the filesystem etc.

I was thinking that it'd be cool to have the ability to upload new files by drag-and-dropping it. And I think that this could make a life more easier for a lot of OpenSlides users, because it's easier to drag file to the Files menu rather then pressing a button, filling in all the info and then clicking Save. And it should save some time if you need to upload a lot of time (especially if you don't have that much time, like in our case).

The way I see it, is to add the drag-and-drop area to `Files` area so the user can drag the file from the filesystem to it. The user would also be able to upload file the old way.

The new workflow would be something like that:
- user goes into `Files` tab and drags the file onto the area
- a `New file` dialog is displayed with the file path filled in
- user fills in other values, like file name, hidden/not hidden etc. and press `Save` and it's saved.

I want to implement it by myself, since it doesn't seem like a big deal to me (although I didn't look at the code structure thoroughly yet) and make a PR to this repository.

What do you think about this idea? Do you think that's a good idea and would you merge it into your repository if it'll be implemented properly?

(I've opened this issue as a platform for discussion, because I had some cases when I implemented some feature for some tool that I use and the author said that they didn't need it, making this work pointless, I don't want to implement something that won't be merged.)

Thanks in advance.

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Please try it!
Also @serge1peshcoff , I do not know, why I cannot assign you...

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I will try it in today evening or tomorrow evening, gotta travel to another city tomorrow

**Comment by serge1peshcoff** [comment]
Actually I've looked into this now and it looks really nice!
The only thing is, for me the upload window is not closing after all files are uploaded, and if I'll upload all files and press 'Upload' again, it shows an error that the file with this name already exists. It'd be really nice if it would auto-close after uploading all the files. Or, even better, remove the file from this view if it's uploaded correctly and leave only files with errors there.
Can this be implemented?

Thanks in advance.

**Comment by FinnStutzenstein** [comment]
Yes, I thought that there is a need of seeing all files uploaded, so that you can click on 'clear list' and upload more files. Do you think this 'clear list' thing is necessary? If no, I would remove it and make the form close, if all uploads are completed.
Also I forgot a 'delete' is you select the wrong file. I'll add this, too.

**Comment by serge1peshcoff** [comment]
I suggest removing the file from the list if it's uploaded successfully, so the user will see only the files where the upload error occurred, and if no errors were detected, the window would just close (and probably the message with something like 'All files were uploaded successfully." would appear)

What do you think about that?

**Comment by FinnStutzenstein** [comment]
Update: Now with better error handling and auto-close if all uploads have been successful.

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein I just tried it, it looks awesome, thanks a lot ;)

**Comment by emanuelschuetze** [comment]
Changelog entry added. Ready for merge.

**Pull request merged**
