### PR TITLE
Login form

### LINKED ISSUE #1762: Login button does not work
See #1756.

Click Continue as guest to close the model. The try to click "Login" ... nothing happens.

### PR DESCRIPTION
**Pull request by emanuelschuetze**
Fixes #1762 and uses 'guest_enabled' info from pull request #1763.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Ok. if the case guest enabled is tested.

**Comment by emanuelschuetze** [comment]
Yes, it is tested with/without guest enabled.

**Comment by ostcar** [comment]
@emanuelschuetze please rebase, then merge

**Comment by emanuelschuetze** [comment]
Rebased.

**Pull request merged**
