### PR TITLE
Secure Mediafiles and check view permissions

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Yes this is right, but I think if the system admin dismisses this, this is not our fault ;)
We may write a warning into the big mode readme.

**Comment by normanjaeckel** [comment]
Hm. The system admin is not able to check out permissions and hidden flags of mediafiles in Nginx area ...

**Comment by FinnStutzenstein** [comment]
He should not deliver mediafiles with nginx, only the staticfiles. So the url /media/ should be forewarded to OpenSlides.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
