### PR TITLE
Fixed Path error

### PR DESCRIPTION
**Pull request by sanojkl**
The readme path is different, fixed

### CODE REVIEW

**Comment by sanojkl** [comment]
pip build didnt work, please wait i post update

**Comment by FinnStutzenstein** [comment]
We drop pip support in the newest version since the python part of OpenSlides cannot run stand-alone anymore. You need to have additional services spin up to get it working. I think that I forget to delete the setup.py

**Comment by sanojkl** [comment]
@FinnStutzenstein ok, then you should laso update the wiki make release

**Comment by emanuelschuetze** [comment]
Closed because pip support was removed, see #5852

**Pull request closed without merging**
