### PR TITLE
Work on check_json.py

### PR DESCRIPTION
**Pull request by reiterl**
Update check_json.py:
- tests for missing fields and extra fields
- type checks
- relation checks (relation, relation-list, generic-relation, generic-relation-list)

Note it doesn't check template fields.

Update the example-data.json and a bit the inital_data.json.

### CODE REVIEW

**Comment by jsangmeister** [comment]
Please request a review instead of manually moving it to the review column.

**Comment by FinnStutzenstein** [comment]
I'll do some more changes.

**Comment by FinnStutzenstein** [comment]
I updated the checker and added it to the CI. Templatefields are still missing.

**Comment by FinnStutzenstein** [comment]
I'll merge it for now - the TODOs are documented here: #5826

**Pull request merged**
