### PR TITLE
Angular: downgrade ui-tree to fix the agenda sort view

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Successfully tested.

**Comment by normanjaeckel** [comment]
Please add somewhere a short note which version works which not and want to do if a new one is released. Then rebase and merge.

**Comment by ostcar** [comment]
That is done in the bower file. If someone wants to update to a newer version, this person has to test if the newer version works.

**Comment by normanjaeckel** [comment]
Hm. There is not mentioned that version 2.10.x does not work. (Like `"~2.x,!2.10") I can merge this nevertheless. We can keep this in mind in issue #1717.

**Pull request merged**
