### PR TITLE
fix double PDF Head in Motions (fixes #3025)

### LINKED ISSUE #3025: Motion: PDF-headers duplicated while line-number-outside
When using the outside line number mode, headers get displayed twice in PDF.

bildschirmfoto von 2017-03-01 12-09-39

surprisingly, it only happens when using line numbers outside. With line numbers inside and line numbers off, everything works as it is supposed to.

### PR DESCRIPTION
**Pull request by tsiegleauq**
This is a hack. I do **not** plan to keep the code this way.
This hack is necessary due to the weird HTML Code structure introduced recently.
Currently: Outside Line Numbers and HTML Head-Tags do not get along well.
This hack helps to deal with that.

As explained before, the clean way is to ensure HTML headers in Motions keep the following structure:
```
<span>
<h1>
...
</h1>
</span>
```

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
see example pdf:
issue3025

**Comment by tsiegleauq** [comment]
> So, after rebasing your branch on top of current master (git rebase master) your fix does not work...still double header lines...

how can that be? Seems like your rebase did overwrite the changes.

> And there is introduced a new bug: the summary of change recommendations is sorted descending (instead of ascending)

only the `<HX>` content of the parser was altered in the pull request. This seems completly unrelated.

**Comment by emanuelschuetze** [comment]
Retested again after rebasing on top of current master:
Works now as expected! Also the recommendation sorting bug in gone. Seems to be a rebase/cache problem on my side.
I rebased and pushed the commit to your branch. Ready for merge.

**Comment by emanuelschuetze** [comment]
I added a second commit (similar to first one) which fixes #3095.

**Pull request merged**
