### PR TITLE
Rename and check "can see extra data" permission.

### PR DESCRIPTION
**Pull request by emanuelschuetze**
This PR replaced #5421.

See [users/serializers.py#L32](https://github.com/OpenSlides/OpenSlides/blob/47795b57d120ef2a17a5fea072c239b0016191a3/openslides/users/serializers.py#L32) for checking server-side serializer for "can see extra data" permission.

### CODE REVIEW

**Comment by tsiegleauq** [comment]
It does not replace - #5421, the user list was not altered here.
Furthermore, it does not target the issues I encountered in #5421.
"gender" and "email" are, apparently, missing in the user auto update for every user except admins.

**Comment by tsiegleauq** [comment]
tested. Gender is still in extra-data. For users who manage a list of speakers but should not see extra data, this might not be acceptable.

However, giving the LOS-manager group that field might be an acceptable compromise.
Not entirely sure what to do then, thus I simply fix travis for now

**Comment by emanuelschuetze** [comment]
@tsiegleauq Please move [this gender line](https://github.com/OpenSlides/OpenSlides/blob/47795b57d120ef2a17a5fea072c239b0016191a3/openslides/users/serializers.py#L33) to USERCANSEESERIALIZER_FIELDS. Then gender should be visible for all users with can see names.

**Comment by emanuelschuetze** [comment]
I updated user detail to show gender field for all users.

**Pull request merged**
