### PR TITLE
Cleanup and resolving ToDos

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@tsiegleauq There are some lines that needs attention:

 - base-poll-pdf-service.ts:74
 - poll-form.component.html:11
 - poll-form.component.ts:208
 - poll.service.ts:251  
 - poll.service.ts:257  
 
Next to sean, these places may be refactored by @GabrielInTheWorld or @jsaalfeld (I'm not sure, who is the right one):

 - attachment-control.component.ts:100
 - progress-snack-bar.component.scss:10
 - motion-poll.component.ts:30

Please look at the linked lines (mostly TODOs) and either resolve or remove these remarks/todos.

**Comment by jsaalfeld** [comment]
I don't think I have written anything of the requested changes.

**Comment by FinnStutzenstein** [comment]
You and @jsangmeister  have a very long common prefix in your usernames ;)

**Comment by tsiegleauq** [comment]
> base-poll-pdf-service.ts:74

I and forgot to remove the todo

> poll-form.component.html:11

The way this section was intended would not resolve the todo. Thus, it needs to be removed.
The core task is to set our dynamic form values to write-only / disabled.
So, nothing trivial to do right now, will take care about this later.

> poll-form.component.ts:208

Was another todo I forgot to remove. I suppose this was due to the multiple anonymous votes-method.

> poll.service.ts:251
> poll.service.ts:257

Solved. Requires the property "type" in the PollData interface and thus as Projector data. Apparently, the server already sends the correct data.

> attachment-control.component.ts:100

This function is abstract in the (grand)parent and (apparently?) not required for this specific control. Adjusted the comment accordingly

> progress-snack-bar.component.scss:10

Created a theme

> motion-poll.component.ts:30

superclass only has the protected property `_poll`. Remove the comment.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein ping. Review, Rebase, Merge.
I adjusted the title since there are some more leftover things to do bevore this can go into master.

**Pull request merged**
