### PR TITLE
Sort list of speakers (Fixes#1662)

### PR DESCRIPTION
**Pull request by emanuelschuetze**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Still in progress!

@normanjaeckel: The client side ordering is done in this pull request. But I need a server side function to save the reorderd list of speakers.

**Comment by emanuelschuetze** [comment]
Added sort_speakers POST request. Ready to add function on rest api.

**Comment by emanuelschuetze** [comment]
Rebased. Ready for review and merge.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
