### PR TITLE
Motion block

### PR DESCRIPTION
**Pull request by normanjaeckel**
There are some TODOs. You can search for them if you like.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Added some stuff: Ready for @emanuelschuetze. Please also have a short look at the TODOs.

**Comment by normanjaeckel** [comment]
@emanuelschuetze You have to remove database before using this commit because of the new ProjectionDefault. This is no problem for the migration path from 2.0 to 2.1, only for development.

Next problem: The generic link building in agenda fails because it does not support camel case.

**Comment by emanuelschuetze** [comment]
@normanjaeckel I added a commit with my template improvements. Also with the new button in motion block detail template. Let me know if you finished with your work...

**Comment by normanjaeckel** [comment]
All done.

**Comment by emanuelschuetze** [comment]
Added minor template changes. Rebased and resolved conflicts. Added Changelog entry. 
Ready for merge.

**Comment by normanjaeckel** [comment]
Ok, Travis failed.

**Pull request merged**
