### PR TITLE
Add default_vote_weight default

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@GabrielInTheWorld This should fix https://github.com/OpenSlides/openslides-backend/issues/523

### CODE REVIEW

**Comment by jsangmeister** [comment]
I think this has to be `1.000000`, right? So we stay consistent with our decimal schema.

**Comment by FinnStutzenstein** [comment]
Can the backend handle a "1" or does it need to have 6 decimals?

**Comment by jsangmeister** [comment]
It should be able to, but I still prefer to have the default values match the schema of the field.

**Comment by FinnStutzenstein** [comment]
Ok, done in #5962

**Pull request merged**
