### PR TITLE
Bugfix for #2770

### PR DESCRIPTION
**Pull request by CatoTH**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Tested: Now, the pdf of problematic motion is created successfully (with outside line numbers). But the line numbers are displayed only in the first line of each paragraph. The other line numbers are missing. Example:

```
1 foo foo foo
   foo foo foo
   foo foo foo

4 bar bar bar
   bar bar bar
   bar bar bar
``` 

Looks like this is also a bug in master. But I can't test which commit has introduced - maybe the new pdfmake? @CatoTH Can you try to fix this that we get all line numbers in pdf?

**Comment by CatoTH** [comment]
@emanuelschuetze This sounds a bit like what I just reported here: https://github.com/OpenSlides/OpenSlides/issues/2777
Maybe I'll have some time tomorrow evening, but no promises. Maybe @tsiegleauq has more time?

**Comment by tsiegleauq** [comment]
I would take a look on this next wednesday.

**Comment by emanuelschuetze** [comment]
I moved the open problem to #2777. So this pull request fixes the pdf build error.
@normanjaeckel Please review.

**Pull request merged**
