### PR TITLE
Disable general no/yes depending on poll method

### PR DESCRIPTION
**Pull request by tsiegleauq**
During the creation of an assignment poll:
Disable and unset the general yes control if the poll method is "yes"
Disables and unset the general no control if the poll method if "no"

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
"General approval" is still enabled in ballot after creating a ballot (with unchecked 'General approval')! Try it with Yes election!

**Comment by emanuelschuetze** [comment]
Same for "General rejection" in a "No" election.

**Comment by tsiegleauq** [comment]
that's weird. `global_yes` is not part of the request for "Y" polls and vice versa for "No" polls. Something actively ignores form values and the server assumes that the absence of values implies `true`.

**Comment by tsiegleauq** [comment]
well that's angulars forms... apparently, disabled values usually get ignored. Can be solved accessing the raw values.

**Review by emanuelschuetze — APPROVED** [review]
OK now. I rebased (because your autoupdate submodule was outdated)

**Pull request merged**
