### PR TITLE
parse UL/OL list styling in PDF (Fixes #3228)

### LINKED ISSUE #3228: Motion PDF change recommendation: delete whole LI element
When we delete a whole LI element using change Recomendation, the parser completely ignores that.
Change Reco builds a new UL List for the element we striked through.
The UL list then got the class `<ul class="delete">`

We currently only parse inline css classes in spans iirc.

Somebody please assign me to this

### PR DESCRIPTION
**Pull request by tsiegleauq**
Enables parsing of style attributs for UL and LI lists

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@tsiegleauq This PR introduces a new problem. Compare [wrong-list-motion.pdf](https://github.com/OpenSlides/OpenSlides/files/988850/wrong-list-motion.pdf) (This PR) to [current-master-motion.pdf](https://github.com/OpenSlides/OpenSlides/files/988852/current-master-motion.pdf). Lists get too much padding, if linebreaks are in there.

**Comment by tsiegleauq** [comment]
This is not **new** but **old** behaviour. I pushed [this pull request](https://github.com/OpenSlides/OpenSlides/pull/3235) on the same day which addresses these kind of behaviour.
This got not rebased because these have been pushed on the same day.

Please check for corresponding pull requests and issues next time...

**Comment by tsiegleauq** [comment]
I also rebased the branch again. So this should not happen anymore.

**Comment by emanuelschuetze** [comment]
Mmh, I can't see any improvements here compared with current master. There is still a strange behaviour with deleted list items and the corresponding line number and indentation. See this motion PDF example where line 18 was deleted:

issue-pdf-list-item

**Comment by tsiegleauq** [comment]
@emanuelschuetze :

The list content should not have any styles (e.g. red backgrounds) without  the `ComputeStyle(list, styles);` line in `UL` and `LI`

This is the content of this pull request. With your screenshot, you are refering to a [different issue](https://github.com/OpenSlides/OpenSlides/issues/3229).

**Comment by emanuelschuetze** [comment]
Sorry, but with your pullrequest I get the same result as with master. See my new pdf example with two removed and formatted list items:

issue-pdf-list-item2

The formatted (colored) words are not crossed out...

**Comment by FinnStutzenstein** [comment]
Funny thing.. I do not get the wrong lists in this PR but neither in the current master. My lists are exactly the same as displayed in the web view:
pdflist
@emanuelschuetze may post his motion quellcode.

**Comment by tsiegleauq** [comment]
apparently, constructions like `<ul class="delete">` are not appearing anymore, so this feature might not be needed anymore. I close this PR then.

**Pull request closed without merging**
