### PR TITLE
Projector requirement

### PR DESCRIPTION
**Pull request by normanjaeckel**
Heavy changes in projector/autoupdate/permission related system. There are a lot of issues to do. Please check carefully the functionality of a non privileged projector user. I hope I fixed everything on server side here. There are some TODOs left. @emanuelschuetze or @matakuka If you have some time, please test everything here and let me know, what else is missing.

(Example: Some watch-last-modified user-find constructions are missing on motion detail, assignment details and assignment poll slide.)

Attention: This work won't be compatible with our current master of OpenSlides/openslides-votecollector.

### CODE REVIEW

**Comment by matakuka** [comment]
(user has permissions "can_see_projector only:)

1. at projector page load, *all* users are retrieved, with additional info (name, number, about_me, ...)
2. *all* users are retrieved when a displayed list of speakers is updated.
3. all items currently displayed receive updates
4. users that were updated when not shown, but after projector loading, will then have outdated names.
5. Queries for agenda/item, probably those related to loadRelations, result in 404 (not found) errors (not 403!). 
6. Election titles (from agenda_item) are not shown. On motions, titles *are* shown.
7. On motions, the "state" is missing.
8. The motion on motion slides is cached. If I change the motion text when it is not displayed, and display it again, the projector will show the *old* motion text.
9. When I reload the projector when a agenda/list-of-speakers is displayed, I get only an empty template until the first change in the list of speakers.

I think that at least for non-privileged users, resolving is not a good approach.The info cached is potentially seriously outdated. New items and changed items will only be received if they are changed while displayed. 
In order to get current info, non-privileged users need to get the item/info from the server the moment it is displayed (and then listen for autoupdate in case updates happen while displayed).

Resolving and then autoupdating only works correctly if the user has the rights to *always* see *all* changes. In other cases, old data is cached and data the user may not be allowed to see, (1. and #2322).

**Comment by normanjaeckel** [comment]
> 1. at projector page load, all users are retrieved, with additional info (name, number, about_me, ...)

I can not confirm this: Tested with projected custom slide. No access to rest/users/user seen in server log.

> 2. all users are retrieved when a displayed list of speakers is updated with a user not yet cached.

Confirmed that all users are fetched. This is a bug in SlideListOfSpeakersCtrl where we use User.findAll() instead of just fetching the required users. Server looks ok.

> 3. all items currently displayed receive updates

So no problem here?

> 4. users that were updated when not shown, but after projector loading, will then have outdated names.

Confirmed for list of speakers slide. There is a watch expression missing in SlideListOfSpeakersCtrl.

> 5. Queries for agenda/item, probably those related to loadRelations, result in 404 (not found) errors (not 403!). 

This but I know. I have to care about it (later). I think it is only relevant for hidden agenda items.

> 6. Election titles (from agenda_item) are not shown. On motions, titles are shown.

I can see agenda numbering on assignment slide. But this numbering is only autoupdated if the slide is open. This is a main problem: Slides do not recall their `find` or `findAll` expressions if the projector manager switches between them. Motion and custom slide the same.

> 7. On motions, the "state" is missing.

I can not confirm. I can see state and autoupdate if the slide is open. If not we have the same problem as described in my comment to no. 6.

> 8. The motion on motion slides is cached. If I change the motion text when it is not displayed, and display it again, the projector will show the old motion text.

The same as no. 6 and 7.

> 9. When I reload the projector when a agenda/list-of-speakers is displayed, I get only an empty template until the first change in the list of speakers.

I can not confirm. I open a list of speakers slide and then press F5. The slide is correct afterwards.

**Comment by matakuka** [comment]
I'll later retest the things you could not confirm.
My setup for the test was: fresh database, user managing the slides on firefox, user with can_see_projector only on chrome.

**Comment by normanjaeckel** [comment]
Please test custom slide with my new commit. Maybe this is a valid approach.

**Comment by normanjaeckel** [comment]
We use another approach, see #2388.

**Pull request closed without merging**
