### PR TITLE
pro/contra speakers and notes for point of order speakers

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Not pretty, but all functionality should be there.

**Review by tsiegleauq — CHANGES_REQUESTED** [review]
although one cannot manage the list of speakers they can mark themselves using the star

**Comment by FinnStutzenstein** [comment]
Right, this is wanted. There is a new config to disable this (should be disabled by default)

**Comment by FinnStutzenstein** [comment]
@tsiegleauq I added the projector

**Comment by tsiegleauq** [comment]
ok. Can be tested.

**Comment by FinnStutzenstein** [comment]
Note: https://github.com/OpenSlides/openslides3-autoupdate-service/pull/162 is merged. I've updated the autoupdate submodule.

**Review by emanuelschuetze — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein One important issue (can be done later in new PR):
If the config "agenda_list_of_speakers_speaker_note_for_everyone" is disabled the note is visible for LOS-managers only - the submitter can NOT see his/her own note!

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Second issue: The mark-speakers-with-star-button should work as radio button. The server should disable pro/contra option if client sends mark option. (Otherwise the client would have to send two requests...)

**Comment by emanuelschuetze** [comment]
issues splitted out to #6035

**Pull request merged**
