### PR TITLE
Added karma tests for angular.js to travis.

### PR DESCRIPTION
**Pull request by emanuelschuetze**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@normanjaeckel Travis failed. Please wait with merge until @CatoTH fixed the karma tests in a new pull request. Then I rebased and travis should pass all tests.

**Comment by emanuelschuetze** [comment]
TODO: rebase after merge of #3072

**Comment by emanuelschuetze** [comment]
rebased.

**Comment by normanjaeckel** [comment]
Test failed.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Ready for merge. Karma tests successfully integrated.

**Pull request merged**
