### PR TITLE
Added new flag for states to hide motions from submitters.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
We have to fix the caching problem first, see my email @ostcar.

**Comment by emanuelschuetze** [comment]
Rebased, now with caching fix #4237

**Comment by emanuelschuetze** [comment]
Successfully tested. Works with:
``` 
required_permission_to_see="motions.can_manage",
hidden_for_submitter=True
```

But as discussed with @normanjaeckel we want to improve the permission check by introducing a new combined choice field which replaces both flags (required_permissions_to_see and hidden_for_submitter):
1. all users (with 'motions.can_see') can the the motion in this state
2. (1) without normal users
3. (2) without submitters
4. (3) without 'motions.can_manage_metadata'
5. only 'motions.can_manage'

**Comment by emanuelschuetze** [comment]
I'll test and rebase it (to fix travis errors)

**Pull request merged**
