### PR TITLE
Subtitles for projected elements in the projector detail view

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Additionally, I cleaned up some agenda subtitle and general title related code.

@tsiegleauq Can you do the styling in the projector detail component? I just added the subtitles behind the titles.

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Hint: Travis is currently offline...

**Comment by tsiegleauq** [comment]
done

**Comment by tsiegleauq** [comment]
The code looks like the ellipsis was not there before. Since the Sorting List was made with multiple display table, I would need to rewrite it in order to get the ellipsis working. I'd rather do that separately since that's gonna take some more effort

**Comment by FinnStutzenstein** [comment]
..Does this mean, that it is ready to merge for the subtitle-part and the ellipsis-styling is related to other code parts that should be done in another PR?

**Comment by tsiegleauq** [comment]
Als far as I am concerned, it does. Yet it depends on Emanuel after all.

**Comment by emanuelschuetze** [comment]
> The code looks like the ellipsis was not there before. Since the Sorting List was made with multiple display table, I would need to rewrite it in order to get the ellipsis working. I'd rather do that separately since that's gonna take some more effort

Ok, then we don't need ellipse and we can merge this PR.

**Pull request merged**
