### PR TITLE
Fixed remarks (closes #3760)

### LINKED ISSUE #3760: Fix old remarks
Pleas fix remarks here (https://github.com/OpenSlides/OpenSlides/pull/3734) and here (https://github.com/OpenSlides/OpenSlides/pull/3723). Thanks.

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Also removed the object replacement character (U+FFFC).

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Please restart travis..

**Comment by emanuelschuetze** [comment]
Rebased.

**Comment by normanjaeckel** [comment]
Still open: some unicode (U+FFFC) object replacement characters

**Comment by emanuelschuetze** [comment]
Yes, this was fixed in #3647 - see https://github.com/OpenSlides/OpenSlides/pull/3647/files#diff-47d0e7ce5de2086fff0018138a84940d

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
