### PR TITLE
Agenda duration and estimated time (closes #2109)

### LINKED ISSUE #2109: Add agenda estimated time (sum of the time of all agenda items and calculated end)
This was a feature of 1.7

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
- Changed the field duration from charField to IntegerField (+ migration)
- added hourMinFormat for input fields
- added osMinToTime (minutes --> (h)h:mm)

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
wrong time format in string "Estimated end: 17:0" (expected: 17:00)

**Comment by emanuelschuetze** [comment]
> wrong time format in string "Estimated end: 17:0" (expected: 17:00)

Fix confirmed.

**Comment by emanuelschuetze** [comment]
Rest works good. A date-time-picker for config field would be great (create an issue if you will do it later in new PR).

@normanjaeckel Ready for review.

**Comment by normanjaeckel** [comment]
Ready to merge.

**Comment by emanuelschuetze** [comment]
ok

**Pull request merged**
