### PR TITLE
Fixed get_queryset method of ItemViewSet. Fixed #2027.

### LINKED ISSUE #2027: Users without 'see internal items' permission gets 404 for existing (closed) items
It seems that #2026 has introduce a new bug:
* Start with new DB.
* Deactivate the 'see internal items' permission for guests.
* Activate guests.
* Create new agenda item. -> Guest can see this item in /rest/agenda/item but not in /rest/agenda/item/1 (404).
* Set item to closed. -> Guest can not access to /rest/agenda/item/1/ -> gets a 404

Sometimes a reload helps to see the closed item in agenda list view. Here is something broken... Important for next beta release.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
The test of https://github.com/OpenSlides/OpenSlides/issues/2027#issue-138107526 works now: (closed) agenda items are visible for guests.

But there is still a (related) bug:
* As admin: Create a motion (and show motion as hidden item in agenda).
* Then try as guest to open motion detail view -> 404 of /rest/agenda/item/3

**Comment by emanuelschuetze** [comment]
Note:  The guest has no 'see internal item' permission.

**Comment by normanjaeckel** [comment]
This is a client error. The client should not try to fetch agenda/item URL if the item is hidden. Please merge and check this in a separate issue.

**Comment by emanuelschuetze** [comment]
New issue #2038 created.

**Pull request merged**
