### PR TITLE
Add vscroll for motion detail

### PR DESCRIPTION
**Pull request by tsiegleauq**
Adds virtual DOM scrolling for the Motion Detail View. Virtual Scrolling only applies for the Diff View

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
(rebase on master to fix the python tests)

**Comment by tsiegleauq** [comment]
should be done from my part. Have done all I can to increase the performance. The height of the elements is usually unpredictable which can result in flickering scrolling. Worked okay-ish for roughly 800 automatically generated amendments.
using `go build && ./performance create_amendments -a 800` from the performance folder.

@CatoTH I created a stackblitz to show what is going on any why virtual scrolling in angular works.

https://stackblitz.com/edit/vscroll-buffer-example?file=src/main.ts

see that one and your browsers console output

**Comment by CatoTH** [comment]
@tsiegleauq So do you have any hint what exactly I should implement? Or what I should try to avoid from being called immediately when the motion details are opened?

**Comment by tsiegleauq** [comment]
As far as I observe, the detail diff functions were called immediately
after one enters the motion detail view. This logic was probably fired by
one of the constructors, since they appear before the onInit function.
The logic to render a diff needs to be fired "in a lazy way", meaning, just
when the diff was accessed yet not in advance.

Currently I suppose we were calculating the diff in advance to support
caching and fluid scrolling once the whole view was calculated.
Unfortunately this can take as much as 700ms for a single diff view which
could sum up to quite a view seconds of pre calculation.

Using virtual scrolling, one would invest the 700-something ms while
scrolling through the virtual DOM (the list of changing objects) but not in
advance. In theory, this should result in a faster rendering of a motion
detail view, even though it has hundreds of amandments or change
recommendations. The calculation effort is just needed later when the user
actually needs to see a specific amendment or change reco.

Tobias Hößl ***@***.***> schrieb am Fr., 9. Apr. 2021, 19:34:

**Comment by tsiegleauq** [comment]
Closing. Certain Code fragments in here should not get lost. The required features will be in a new PR

**Pull request closed without merging**
