### PR TITLE
Change recommendations for amendments

### PR DESCRIPTION
**Pull request by CatoTH**
Not ready to be merged.

What works:
- Creating, editing and deleting change recommendations for paragraph-based amendments
- Original, Changed and Diff view of an amendment, where the three terms refer to the amendment in relation to the change recommendations
- Setting the status of change recommendations
- The overhauled amendment is shown in the Diff / Final view of the motion

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Another issue:
- set config for 'default text version for change recommendation' to 'diff version'
- Create a new change-recommendation in an existing motion
=> motion detail view shows original version instead of switching automatically to diff version

**Comment by CatoTH** [comment]
> Looks good. I found one bug:
> After creating new amendment the amendment-detail view shows the _full_ context instead only the modified paragraph (with checkbox at the end). Reload helps. Can you fix it please?

Can you tell me how to reproduce this? Somehow I can't see it:

**Comment by emanuelschuetze** [comment]
How to reproduce the error with this branch:
- clear cache/local storage
- create new database
- activate amendment config
- create new motion with some paragraphs
- create new amendment for first paragraph
=> amendment detail shows motion with _full_ context (no checkbox available)
=> console shows a TypeError:
```
TypeError: Cannot read property 'isParagraphBasedAmendment' of undefined
    at MotionDetailComponent_Template (motion-detail.component.html:994)
```

Always reproduceable for me.

**Comment by CatoTH** [comment]
Ok, I hope it is fixed now. The relevant change for that would be https://github.com/OpenSlides/OpenSlides/pull/5304/files#diff-9f3bc5397a73edb361f0245a80a86728R667 . The error thrown should fixed, too, though not primarily responsible.

**Comment by emanuelschuetze** [comment]
> set config for 'default text version for change recommendation' to 'diff version'

Ok, this is fixed now. Thanks.

> Create a new change-recommendation in an existing motion
> => motion detail view shows original version instead of switching automatically to diff version

This behavior still exists. But we can fix it later in a new PR.

**Pull request merged**
