### PR TITLE
Update cache for attachments (fixes #4055)

### LINKED ISSUE #4055: Deleting Mediafile does not update attachment-ids
- upload files
- create motion with attachments (possible soon:tm: but should be the same in the old client)
- delete the attached file from Mediafiles
- see `/rest/motions/motion/`

expected: `"attachments_id": []`
result: `"attachments_id": [<ID-of-non-existing-mediafile>]`

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@normanjaeckel This is a bit hacky. Do you have a better approach or is it ok?

### CODE REVIEW

**Comment by normanjaeckel** [comment]
We may have the same problem for tags and also for other relations like categories and so on. So we need a generic solution. I will think about it.

**Comment by normanjaeckel** [comment]
@ostcar Any idea here?

**Comment by FinnStutzenstein** [comment]
I do not know the django code exactly, but we might intercept the m2m relations. If we had an explicit through-model (like subitters), we could add the logic there. For attachements, django manages this model (and the related table in the db). As a first step we can try to override the classes (e.g. the related manager) which take care about this relationship.

**Comment by FinnStutzenstein** [comment]
We should definitly create an issue collectung these current problems and move the discussion there. If we find something, this chage can easily be reverted.

**Comment by normanjaeckel** [comment]
See #4201.

**Pull request closed without merging**
