### PR TITLE
Setting for the mediafile database tablename

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by gsiv** [comment]
It appears that the database is still hard-coded as `mediafiledata`.  It also needs to be configurable for this feature to be useful.

For some context, the goal is to be able to store the media file table inside OpenSlides' main database, possibly in a separate schema.

**Comment by FinnStutzenstein** [comment]
Please look at the new commit. For consistency: I would like to rename all `DATABASE_*`  for the mediafile DB to `MEDIAFILE_DATABASE_*`. Is it ok for you?

**Comment by gsiv** [comment]
> Please look at the new commit.

Thanks, I have tested it successfully in combination with https://github.com/OpenSlides/openslides-media-service/pull/21.

For the server environment I added these variables to the YAML template:

```
    MEDIAFILE_DATABASE_NAME: "read_env(`MEDIAFILE_DATABASE_NAME')"
    MEDIAFILE_DATABASE_TABLENAME: "read_env(`MEDIAFILE_DATABASE_TABLENAME')"
```

For the media service:

```
      - DATABASE_NAME=read_env(`MEDIAFILE_DATABASE_NAME')
      - DATABASE_TABLE=read_env(`MEDIAFILE_DATABASE_TABLENAME')
```

A complete list of these configuration variables should probably be added to `.env` and the templates.

> For consistency: I would like to rename all `DATABASE_*` for the mediafile DB to `MEDIAFILE_DATABASE_*`. Is it ok for you?

Sure, go ahead; it shouldn't make a difference.

**Comment by gsiv** [comment]
By the way, there is a hard-coded `INSERT INTO mediafile_data` left here: https://github.com/OpenSlides/OpenSlides/blob/d86fcd80b74356b18624db4d11d3b457aaa3449b/server/openslides/mediafiles/management/commands/export_mediafiles.py#L30

I think it might be legacy command used for migrations and could be removed.  If it's still required it should also be updated, I'd say.

**Comment by FinnStutzenstein** [comment]
I added the changes. Please check, if it fits your needs.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein @gsiv ping

**Comment by FinnStutzenstein** [comment]
> @FinnStutzenstein @gsiv ping

Only @gsiv ;)

**Comment by gsiv** [comment]
I already successfully tested a previous version of this PR.  The changes since then should be minor and the patch looks good on first glance.

What isn't perfect but acceptable for now:

 * the new settings haven't yet been added to .env
 * the way variables are being passed to psychopg2 is not very robust, if I'm not mistaken

All in all, this PR is ready to merge, IMO.

**Comment by FinnStutzenstein** [comment]
> I already successfully tested a previous version of this PR. The changes since then should be minor and the patch looks good on first glance.

Top

> * the new settings haven't yet been added to .env

I can fix this

> * the way variables are being passed to psychopg2 is not very robust, if I'm not mistaken

You mean because direct template replacements are used (`f"INSERT INTO {mediafile_database_tablename} (id, data, mimetype) VALUES (%s, %s, %s)",`)? psycopg2 does not allow placeholders for these parts of the query. Since the user cannot put things into this variable, it is safe to use.

**Comment by gsiv** [comment]
> You mean because direct template replacements are used (`f"INSERT INTO {mediafile_database_tablename} (id, data, mimetype) VALUES (%s, %s, %s)",`)? psycopg2 does not allow placeholders for these parts of the query. Since the user cannot put things into this variable, it is safe to use.

All the better.  I just kind of have the expectation that setting a table name with, e.g., spaces would break the query.

However, I'm not sure and if memory serves me right, we already decided that it's good enough anyway.  I just wanted to explicitly mention it once before the PR is closed.

**Comment by FinnStutzenstein** [comment]
> > * the new settings haven't yet been added to .env
> 
> I can fix this

Done

> All the better. I just kind of have the expectation that setting a table name with, e.g., spaces would break the query.

Right, can be fixed when someone stumbles upon it I guess.

**Pull request merged**
