### PR TITLE
Added general abstain/no fields for assignments. Used in votes mode.

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
@emanuelschuetze Please check this with the voting plugin together. The terms `Abstain` and `No` used several times in the view should be changed. What is the right wording for it?

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
As disscussed: Add "no" field to ballot paper. Add "no" and "abstain" to PDF and projector.
I'll think about a generic wording...

**Comment by FinnStutzenstein** [comment]
Travis needs to be restarted..

**Comment by FinnStutzenstein** [comment]
@normanjaeckel @emanuelschuetze please review. This should be merged soon..

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please review later. We have to merge it now.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
