### PR TITLE
Disable the future-lock when updating the restircted data cache

### PR DESCRIPTION
**Pull request by ostcar**
Before this commit, there where two different locks when updating the restricted
data cache. A future lock, what is faster but only works in the same thread. The
other lock is in redis, it is not so fast, but also works in many threads.

The future lock was buggy, because on a second call of update_restricted_data
the same future was reused. So on the second run, the future was already done.

I don't see any way to delete. The last client would have to delete it, but there
is no way to find out which client the last one is.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Rebased.

**Comment by normanjaeckel** [comment]
Sorry I do not understand why we sort all imports with one . before the imports from the higher level now (two ..).

**Comment by ostcar** [comment]
The new version of isort did it. This was my first commit after the new release and as it seems I am the only one how calls isort.

I had the isort change in a separate commit, but emanuel merged it together.

If you don't like the stile, please change the config or open an issue on the isort project.

**Comment by FinnStutzenstein** [comment]
Reverted with #4468..

**Pull request merged**
