### PR TITLE
Projector indicator list view tables

### PR DESCRIPTION
**Pull request by tsiegleauq**
Shows a projector indicator in the list view tables.
Width is 24px, just as small as mat-icon needs.
Works in every list view that allows projector buttons (which should
cover all where an indicator could be demanded)

(the branch name is misleading)

@emanuelschuetze tell me if you like it

### CODE REVIEW

**Comment by tsiegleauq** [comment]
> Additional wish: Please add an attachment icon if an entry has attachments.

Neither item nor view_icon know about the attachments of their content objects. Since it's another feature it should be handled in another PR

**Comment by tsiegleauq** [comment]
Update:
image

**Comment by emanuelschuetze** [comment]
As discussed, please add background color for testing.

**Comment by tsiegleauq** [comment]
Added background color depending on the current theme. On my mediocre screens I have enough contrast to read everything comfortably. It's currently "accent lighter" cause primary ligher is pretty ugly.

image

image

image

**Comment by FinnStutzenstein** [comment]
IMO the projector icon on desktop, if the operator cannot manage the projector, could be removed. I think it is too much to have the blue background and the icon and the icon looks a bit displaced/lonely.

**Comment by tsiegleauq** [comment]
@emanuelschuetze I guess from all the colors I tried i'd prefer `$background, hover`. Also works fine for the dark themes.

image

**Comment by tsiegleauq** [comment]
Some screenshots:

`background-color: mat-color($background, background) !important;`:
`app-bar` is the same
image

`background-color: mat-color($background, status-bar) !important;`:
image

**Comment by tsiegleauq** [comment]
final version:
image

**Comment by emanuelschuetze** [comment]
Travis hangs... maybe reopen PR helsp...

**Pull request merged**
