### PR TITLE
Update models

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
wait for #5557

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Please do not edit models.txt any more. Make the changes in models.yml.

**Review by normanjaeckel — CHANGES_REQUESTED** [review]
Do not edit models.txt.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Why does the `openslides4-dev` branch do not pass the validation? :(

**Comment by normanjaeckel** [comment]
We have to merge #5587 first and @ostcar or someone else must fix the models validator (because I added a new type of field).

**Comment by normanjaeckel** [comment]
I do not understand why the check does not work. Please rebase the branch and push it again.

**Review by normanjaeckel — APPROVED** [review]

**Comment by ostcar** [comment]
I added the htmlvideo type in the checker. I tagged the version that supports the type with "v0.1.0".

Please first merge #5589 and then rebase this branch on top of it.

We you change to format of the models.yml again and you need a new version of the validator, then the version tag in the github-action has to be updated. This helps to make each commit of this branch work, even when we make backwards incompatible changes to the validator.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel rebased.

**Pull request merged**
