### PR TITLE
Make sure the cache is ensured before manipulating it

### PR DESCRIPTION
**Pull request by ostcar**
This maybe fix the bug, that the cache exists partial.

### CODE REVIEW

**Comment by ostcar** [comment]
I don't understand how this could fix it. It only raises an exception. But if it helps ;)

**Comment by emanuelschuetze** [comment]
@ostcar Right, if I run `migrate` for a fresh database I get this RuntimeError:
```
...
openslides/utils/cache.py", line 138, in change_elements
    "Call element_cache.ensure_cache before changing elements."
RuntimeError: Call element_cache.ensure_cache before changing elements.
```
Do you have any ideas to fix it? I could reproduce it now ;-)

**Comment by ostcar** [comment]
I need the hole traceback. As I said before, I can not reproduce it.

**Comment by emanuelschuetze** [comment]
I can reproduce it not on master but on this [custom branch](https://github.com/Intevation/OpenSlides/tree/dgb3) (maybe because it contains two big workflows):
```
$ git checkout ...
$ rm -r personal_data
$ python manage.py createsettings
$ python manage.py migrate
[..]
  Applying users.0010_auto_20190119_1447... OK
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/__main__.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/core/management/commands/migrate.py", line 25, in handle
    super().handle(*args, **options)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 226, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/signals.py", line 17, in create_builtin_workflows
    workflow_1 = Workflow.objects.create(name='DGB')
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/models.py", line 1234, in save
    super(Workflow, self).save(**kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/models.py", line 93, in save
    inform_changed_data(self.get_root_rest_element())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 98, in inform_changed_data
    handle_changed_elements(elements.values())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 251, in handle_changed_elements
    itertools.chain(elements, history_elements)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 209, in async_handle_collection_elements
    change_id = await update_cache(elements)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 202, in update_cache
    return await element_cache.change_elements(cache_elements)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/cache.py", line 138, in change_elements
    "Call element_cache.ensure_cache before changing elements."
RuntimeError: Call element_cache.ensure_cache before changing elements.
```

**Comment by ostcar** [comment]
Ok. I found it. You have to make sure not to run inform_changed_data inside the migrations. Therefore you can not use Workflow.objects.create(). You habe to use Workflow(); Workflow.save(inform_change_data=False). Look how it is done in master.

The error is in motions/signals.py line 17

**Comment by emanuelschuetze** [comment]
@ostcar Ok, thanks for your hint. I updated the custom signals.py.

**Pull request merged**
