### PR TITLE
Template improvements for tags of agenda items, motions and assignments

### PR DESCRIPTION
**Pull request by emanuelschuetze**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Ok.

**Comment by ostcar** [comment]
@emanuelschuetze do you fix haystack in this pullrequest?

**Comment by emanuelschuetze** [comment]
@ostcar No, the haystack fix comes with a new pull request. Please review and merge this pull request first.

**Comment by ostcar** [comment]
Ok, I first merge the 1.6.x branch into master, because there will be a lot of conflicts.

**Pull request merged**
