### PR TITLE
Added --no-template-caching

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Hi, do you have an idea for this issue (see travis) to fix?
In "normal" execution, we set the `openslides.args` to the parser args. But this does not apply for the tests.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Do you have an idea how to fix this?

**Comment by normanjaeckel** [comment]
Hm. Looks like that the tests also need to add args attribute to openslides module.

Better: Only check args in views if it is not None.

**Comment by FinnStutzenstein** [comment]
Done a new approach. Need more development.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Done some rework. Please review the new approach

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze ready for merge

**Pull request merged**
