### PR TITLE
Squashed old migrations.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Please test migration from v2.3 with data. Please also check config (logo, fonts and thelike).

**Comment by FinnStutzenstein** [comment]
This squashing can not be done at some places, where we have to seperate data and schema migrations for Postgresql. @normanjaeckel please adapt this PR, if you want to have the migrations squashed, but leave migration files seperated, if they are supposed to be seperated (indicated by the postfix `_<number>`).

**Comment by normanjaeckel** [comment]
Rebased. Please test. If a PostgreSQL using instance is on v2.3 the migration to 3.0-dev should work even if I squashed older migration files with unseparated data and schema migrations, right?

**Comment by emanuelschuetze** [comment]
I have no migration errors with the same 2.3.x-database on current master.

**Comment by normanjaeckel** [comment]
If there are no errors it can be merged.

**Comment by emanuelschuetze** [comment]
@normanjaeckel I think you misunderstand my last comment: this  PR does NOT work successfully! Can you please test it again with a database created with 2.3.x?

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel we don't want to squash old migrations anymore.

**Pull request closed without merging**
