### PR TITLE
Fixing CSV import (fixes #2075, fixes #2165)

### LINKED ISSUE #2075: Motion csv import: new category are created multiple and is not assigned to imported motion
* Import motions-demo_de.csv from http://files.openslides.org/csv-examples/
* All categories are marked as 'will be created'.
* After import a category is created two time if this category is listed in two motions.
* The imported motions have no categories assigned (category field is empty).

### LINKED ISSUE #2165: regression: csv import of motions does no longer add new participants
- try to import motions e.g. with this CSV file:

identifier,title,text,reason,submitter,category
Kat A-1,Satzungsänderung,"Die Mitgliederversammlung möge beschließen, in §8 Absatz 1 der Vereinssatzung die Zahl fünf durch sieben zu ersetzen.","Die vielen Aufgaben erfordern eine Erweiterung des Beirates auf sieben Mitglieder.",Dr. Hans Schulze,Kategorie A
B1,Titel 2,Text 2,Begründung 2,Antragsteller 2,Kategorie B
,Titel 3,Text 3,Begründung 3,,

- in the preview you see that OpenSlides will import the motions and that it will add new categories because they don't yet exist AND that it will create a new participant:
motion-import-bug

result: the new categories are correctly created while the new participant is not created. Instead the creator of the imported motion is always the administrator.

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
New order in `$scope.import`:
- List all users and categories, that needs to be created
- make these list entries unique
- create the unique users and categories
- wait, that the creations terminate
- add user and category ids to the motions
- create motions

### CODE REVIEW

**Comment by normanjaeckel** [comment]
Ok. Please move the TODO to an GitHub issue if it can not be solved at the moment.

**Comment by FinnStutzenstein** [comment]
Shall I remove the TODO part from the code or just create the Issue?

**Comment by normanjaeckel** [comment]
You can leave the TODO in the file but should create an issue with a reference to this pull request.

**Comment by normanjaeckel** [comment]
Then rebase and assign to @emanuelschuetze

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Ready with rebasing

**Comment by emanuelschuetze** [comment]
Tested successfully. 
Suggestion: Add info how many categories and users are created.

**Comment by emanuelschuetze** [comment]
> Add info how many categories and users are created.

Tested. Works good. Many thanks! Ready for merge...

**Pull request merged**
