### PR TITLE
Adding new permission to groups during migration from 2.1.1 to 2.2

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Todo: The contenttypes does not exist, if a new DB is created. I'll create them, if needed and django does not crash..

**Comment by normanjaeckel** [comment]
> Todo: The contenttypes does not exist, if a new DB is created. I'll create them, if needed and django does not crash..

If a new DB is created we do not have to migrate permissions to some groups. so you do not have to create the contenttypes. Just skip ... Right?

**Comment by FinnStutzenstein** [comment]
Yes right, if the permission is not found, we skip already

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze This is my os 2.11 db. The migration works fine, the admin group is not created and I can login with admin/admin. You have to remove the two last extensions get the database:
[db.sqlite3.os211.txt](https://github.com/OpenSlides/OpenSlides/files/1802501/db.sqlite3.os211.txt)

**Comment by emanuelschuetze** [comment]
@normanjaeckel Ping

**Pull request merged**
