### PR TITLE
Fixing resolving of Config for projector resolution (fixes #2349)

### LINKED ISSUE #2349: Projector resolution: Config.get() is undefined
Since #2318 I'm getting "Config.get(...) is undefined (/static/js/core/projector.js:70:24)" when working on projector slides.
I think it must be `Config.find(...).then( function() {do something})` in order to work?

(also typo : last-conf.height in line 72 should be last_conf)

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Now resolves Config.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
I do not understand why the config should have to be find here. The config is load in core/base.js. Then is is available in the DS and you should always be able to get it via $scope.config(...).

**Comment by normanjaeckel** [comment]
See #2349

**Comment by FinnStutzenstein** [comment]
Now the controller accesses the config via `$scope.config` but skips if `$scope.config` is not a function. This is the case if `loadGlobalData` hasn't finished yet, because until then `$scope.config` is undefined.

**Comment by normanjaeckel** [comment]
Ok, please rebase.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Ping

**Comment by normanjaeckel** [comment]
Ok.

**Comment by emanuelschuetze** [comment]
Ok.

**Pull request merged**
