### PR TITLE
Support youtube as livestream URL

### PR DESCRIPTION
**Pull request by tsiegleauq**
Allows to use youtube as as live stream url config,
will load the youtube embedded player in an iframe instead
of video.js

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Please show youtube stream in 16:9 livestream window (like videojs player).

**Comment by emanuelschuetze** [comment]
... and we need autoplay (if possible) in youtube player

**Comment by tsiegleauq** [comment]
> Please show youtube stream in 16:9 livestream window (like videojs player).

can only be done by hard setting the width. I did so now.

> ... and we need autoplay (if possible) in youtube player

works in firefox, cannot be done in chrome since 2018
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Tested. Looks very good. Only one failure found:
The door icon is still disabled if a normal user adds to current LoS -> reload required!

**Review by emanuelschuetze — APPROVED** [review]

**Pull request merged**
