### PR TITLE
Collapsable agenda, one panel for each motion comment and hide closed…

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
… agenda items in the item slide.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
One minor remark after testing:
A long title of an agenda item needs more indentation in second line, see screenshot:
agenda_3567

Also a bit more margin-left need the hover menu which is not exactly below the agenda item title.

**Comment by emanuelschuetze** [comment]
Rest looks good.

**Comment by FinnStutzenstein** [comment]
wait for #3565 to be merged and resolve todo...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Please check new commit. This should resolve the style issue.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Ready for merge

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please add Changelog entry. Thx.

**Pull request merged**
