### PR TITLE
Limit selection of files to csv and txt (Fixed #2133)

### LINKED ISSUE #2133: enhancement: missing filter for selection of CSV files
in the section to import participants click on the button "Search" to select a CSV file. Unfortunately this dialog misses a file type filter. Currently it is "*.":
file-selection-filter-bug
but it should be "*.csv; *.txt" since only CSV files (or textfiles in general) are allowed. This eases to find the CSV file in folders with many files.

### PR DESCRIPTION
**Pull request by tsiegleauq**
Increases the version of angular-csv-import and uses the new "accept" function.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Looks good. 
@tsiegleauq It's your first contribution. So you should add your name to AUTHORS file and rebase it together to one commit.

**Comment by tsiegleauq** [comment]
@emanuelschuetze added myself to AUTHORS.

**Comment by emanuelschuetze** [comment]
Ok for me.
@normanjaeckel You can review and merge it.

**Comment by emanuelschuetze** [comment]
As discussed: Please add also file filter for agenda and motions csv import.

**Comment by tsiegleauq** [comment]
@emanuelschuetze 

Motions, and agenda added.

**Comment by emanuelschuetze** [comment]
Looks good.
@normanjaeckel you can review and merge now.

**Pull request merged**
