### PR TITLE
Added history information for motion change recommendations.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
@emanuelschuetze Do you want to get different messages for general update and the change of the internal flag only?

**Comment by emanuelschuetze** [comment]
> Do you want to get different messages for general update and the change of the internal flag only?

I need information about created / updated / deleted and (if possible) published/unpublished.

**Comment by normanjaeckel** [comment]
MotionChangeRecommendation is a root rest element. So I can not easily simulate a changed motion. If you like I can add the motion id to the history information string.

**Comment by normanjaeckel** [comment]
> 
> 
> > Do you want to get different messages for general update and the change of the internal flag only?
> 
> I need information about created / updated / deleted and (if possible) published/unpublished.

Extra information for published/unpublished needs some more afford. Please open an extra issue for this.

**Pull request merged**
