### PR TITLE
Vscroll for user import

### PR DESCRIPTION
**Pull request by tsiegleauq**
Allows to import giant sets of users as CSV.
Tested 500k. The client is fine. The python server and the SQL data base really do not like that.

image

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Nice, this is really fast now. Can you make the preview container a bit larger, so one can see more entries in one page? Maybe the complete page body can be done wider, so the horizontal scrollbar disappears.

**Comment by tsiegleauq** [comment]
> Can you make the preview container a bit larger, so one can see more entries in one page?

In terms of height I was using just enough so you can have the head bar, preview prosa text and the table in one view without scrolling.
```scss
.import-preview-table {
    display: block;
    height: calc(100vh - 200px);
}
```

In terms of width I can use potentially everything, just like in the group or workflow matrix. Not entirely sure if this is more usable or not

**Comment by FinnStutzenstein** [comment]
> In terms of height I was using just enough so you can have the head bar, preview prosa text and the table in one view without scrolling.

Hm ok. The nices way would be to make the scrolling seamless (no inner container) and have a sticky header. But I guess this is too much for now ;)

**Review by emanuelschuetze — APPROVED** [review]
Nice!

**Pull request merged**
