### PR TITLE
Updated Spanish translation. (Fixes #2094)

### LINKED ISSUE #2094: How can i update translation?
I translate to spanish but my instance

http://181.135.123.118:8001/login

Is not translate it 100%

Tnks

### PR DESCRIPTION
**Pull request by emanuelschuetze**
Thanks to johnfelipe!

### CODE REVIEW

**Comment by johnfelipe** [comment]
Is possible put that tranlation in my instance?

**Comment by emanuelschuetze** [comment]
Yes, wait until this pull request is merged into master. Then you can use the master (as described in development instruction file). Or try my branch.

**Comment by johnfelipe** [comment]
This is my instance
http://181.135.63.86:8001/login
where is correct commands for put https://openslides.org/ spanish version?

**Comment by emanuelschuetze** [comment]
Please don't discuss general developement setup questions in (merged) pull requests.
You can ask us for this stuff in IRC or mailing lists. Or read the README and DEVELOPMENT files.

**Pull request merged**
