### PR TITLE
Upgrade to channels 1.x (Fixes #2829).

### LINKED ISSUE #2829: Current daphne needs current twisted
Currently we pin twisted to an older version in the requirements_production.txt: https://github.com/OpenSlides/OpenSlides/blob/master/requirements_production.txt#L9

But this does not work with daphne 1.0.1 which is installed with ```pip install -r requirements.txt```

If you use daphne 1.0.1 with twisted 16.3.2, then you get the following error and daphne does not start at all (even when the message tells you differently) 
```
python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 19:50:25
Django version 1.10.5, using settings 'settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
2017-01-10 19:50:25,915 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,916 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,918 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,921 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4c761c7950>
Traceback (most recent call last):
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 84, in inner_run
    ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/daphne/server.py", line 41, in __init__
    ''' % self.__class__.__name__)
DeprecationWarning: 
                The host/port/unix_socket/file_descriptor keyword arguments to Server are deprecated.
```

Installing the current version of twisted fixes the problem.

Please do not solve this problem by fixing the version of daphne. And if you have to, then please also fix the current version of channels, asgi_ref and asgi_redis

### PR DESCRIPTION
**Pull request by emanuelschuetze**
Remove old incompatible twisted version.
Note: Installation of twisted on windows needs visualstudios build tools!

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@normanjaeckel Some tests in tests.integration.utils.test_autoupdate.TestsInformChangedData failed. Can you look at these results please?

**Comment by normanjaeckel** [comment]
Sorry I just tested new version of channels and daphne but old version of Twisted and it works.

**Comment by normanjaeckel** [comment]
Hm.  This commt https://github.com/django/channels/commit/0826b7997fc30294943913069a63a5a0df3041ad introduced a pending mechanism. I do not know how we should test it in a simple way.

**Comment by normanjaeckel** [comment]
@ostcar Any idea or any hints what the changes in channels 1.0 are?

**Comment by ostcar** [comment]
I have no idea what changed. I don't see any harm in the delay system (even, if I also don't see any win).

The tests can be fixed by importing ```channels.pending_message_store``` and calling ```pending_message_store.send_and_flush()``` before each run of ```get_next_message()```. See also https://github.com/django/channels/pull/480

**Comment by ostcar** [comment]
Please wait for the next channel release. It should come soon.

**Pull request merged**
