### PR TITLE
Add permissions to ListViews

### PR DESCRIPTION
**Pull request by tsiegleauq**
Hides a list view if the user has insufficient
permissions.
Also hides certain other elements where
permissions should apply

Fixes one typo in a python file, where "motion.can_manage" (appending s was missing)

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
Is it correct, that the majority of changes can be reverted, if the authguard works correctly?

**Comment by tsiegleauq** [comment]
Emanuel did not like the idea of the Auth Guard, since it would throw the user out of a view, after clicking a link or something, without a chance of comprehending the problem, in case they don't see anything

**Comment by FinnStutzenstein** [comment]
Hmm, I don't know.. Can you then delte the authGuard?
Some other idea: Put an ngIf around the router-outlet in the siteComponent. Add a function that checks, if the operator has the right permissions for the current route's basePerm (see the authGuard and as an example `users-routing`, line 46). Then we have these permission checks in one central place. I'm not sure if this works, but may be a more generic solution.

**Comment by emanuelschuetze** [comment]
> Some other idea: Put an ngIf around the router-outlet in the siteComponent.

+1
@tsiegleauq can you try it please?

**Comment by FinnStutzenstein** [comment]
Note: With #4450 we can add a possibility to cache the latest permissions from the operator (next to the actual user), too. Then, we do not need to wait for the DS to hold groups to calculate the permission, but can use the cached values until the permissions come in from the DS. This can be done later in another PR.

**Comment by tsiegleauq** [comment]
> Can you then delete the authGuard

The AuthGuard should still check if the user is even logged in or a guest (that's the initial reason for the AuthGuard in the fist place)

> Put an ngIf around the router-outlet in the siteComponent

Well that is an AuthGuard ;-)
- basePerms still need to be added on every route.
- Even if it would, it would imply the basePerm of the site component, not another module
- `ActivatedRouteSnapshot`, accessible over the `canActivate` interface would give you the routes data before accessing it. That's the classical AuthGuard function.

So, I guess we wont be able to check the required permission on the site container.
One slightly cleaner solution **might be** to create a small service or a shared function to read out `AppConfig` and compare it with the operator in one single call, which would _still need to happen in the views of the modules_

So there are some realistic options:
- let the AuthGuard take care and just kick the user out (cleanest)
- create the small check-with-base-perm-service to hide certain elements
- ignore until we know a best design practice

**Comment by tsiegleauq** [comment]
an alternative approach would be, to let the AuthGuard forward the user to an information page that explains why the user cannot access the requested resource. That might be the most "debugable" approach. Users can then directly see "I have no permission to see the XYZ"

**Comment by tsiegleauq** [comment]
- [ ] Smarter AuthGuard. Will probably be done next week

**Comment by tsiegleauq** [comment]
@emanuelschuetze please test

**Pull request merged**
