### PR TITLE
Fixed Nginx settings

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I have a question regarding this: shouldn't the `/media/file-path.extension` request be served as static files instead of being redirected to `/static/templates/index.html`? Or am I misunderstanding something?

**Comment by emanuelschuetze** [comment]
@serge1peshcoff If you do not need a protection for media files (only authorized user with special  permission are allowed to download mediafiles) you can deliver all files as static files, yes. But by default we use the "protection mode" (delivered via django).

**Comment by FinnStutzenstein** [comment]
Hint: See [the protected_serve](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/mediafiles/views.py#L74). It's like a regular server for staticfiles, but checks, if a user has the permission to see this file.

**Comment by normanjaeckel** [comment]
Ok.

**Pull request merged**
