### PR TITLE
Implement vote weight in client

### PR DESCRIPTION
**Pull request by tsiegleauq**
Implements vote weight in client
The user detail page has a new property
change deserialize to parse floats
~change "yes"-voting to send "Y" and "0" instead of "1" and "0"~

### CODE REVIEW

**Comment by tsiegleauq** [comment]
@emanuelschuetze 
Added vote weight to user list overview, user list filter, user list sort
Added exception to user detail and list e-voting is disabled
added vote weight to single voting result

**Comment by emanuelschuetze** [comment]
Please wait with merge until I get more feedback.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein The python tests fail (both local and remote)

**Comment by tsiegleauq** [comment]
Added a config variable to enable/disable vote weight. Currently, only the UI will be affected.

@FinnStutzenstein the server should reset the vote weight of all users back to 1 if the administrator sets "users_activate_vote_weight" to false

**Comment by tsiegleauq** [comment]
Added special treatment for csv (not really tested tho)
Change css for userlist

**Comment by FinnStutzenstein** [comment]
Something is not correct with pytest-asyncio here... :( Is it friday again?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Please test again.

**Pull request merged**
