### PR TITLE
Fixes autoupdate bug for a user without user.can_see_name permission …

### PR DESCRIPTION
**Pull request by normanjaeckel**
…if a speaker is added.

### CODE REVIEW

**Comment by normanjaeckel** [comment]
This would be the "more code" solution for the problem that a user without user.can_see_name permission is able to see correct autoupdate of speakers. We need such code also for motions, assignments, mediafiles and core.

But maybe someone has a better idea?

**Comment by normanjaeckel** [comment]
@emanuelschuetze Fix is now ready for review, test and merge.

**Comment by emanuelschuetze** [comment]
travis failed (flake8 error)

**Comment by normanjaeckel** [comment]
All done.

**Comment by emanuelschuetze** [comment]
Changelog entry added and rebased.

**Pull request merged**
