### PR TITLE
Added view to create related assignment and motion items. Updated ser…

### LINKED ISSUE #1559: Add motion.agenda_item to rest api
Each motion should be able to reference to one agenda item.

### PR DESCRIPTION
**Pull request by normanjaeckel**
…ializers. Fixes #1559.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
See my comment in #1559

**Comment by emanuelschuetze** [comment]
@ostcar This pull request was still in discussion (see my last comment also in #1559) and was not ready to merge! For future please look carefully.

**Comment by ostcar** [comment]
@emanuelschuetze ok, lets try the revert button...

We should stop creating pull requests for branches we do not want to be merged. Any Idea how we can discuss core which is not a pull request?

**Comment by emanuelschuetze** [comment]
> We should stop creating pull requests for branches we do not want to be merged.

No, this was a real pull request from Norman. But before merge we have to note all comments! And my comment was not answered by Norman.

> Any Idea how we can discuss core which is not a pull request?

For non-core code discussion we should wrote an explicit initial comment and title that this PR is not for merge.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Again: Let's discuss my comment in #1559

**Pull request merged**
