### PR TITLE
Refactoring mediafile templates. (Fixes #1839, #1818, #1833)

### LINKED ISSUE #1839: Mediafile template tasks
Mediafile tasks:
* [x] nicer format of timestamp in list view
* [x] uploader not visible/loaded after reload list view
* [x] edit form: remove file upload form element, add uploader form element
* [x] create form: add uploader form element (only if user has manager permissions)

### PR DESCRIPTION
**Pull request by emanuelschuetze**
- uploader not visible/loaded after reload list view
- use same list view style as in other apps
- use dialog for create/edit form
- show error message in form
- edit form: remove file upload form element, add uploader form element
- create form: add uploader form element (only if user has manager permissions)

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can we change the mediafile rest object to a "flat" list, like:
```
{
    "id": 1,
    "title": "TITLE",
    "filename": "file/filename.jpg",
    "filetype": "image/jpeg",
    "media_url_prefix": "/media/",
    "uploader_id": 1,
    "filesize": "1 kB",
    "timestamp": "2016-01-24T08:38:28.698988"
}
```
instead of 
```
{
    "id": 1,
    "title": "TITLE",
    "mediafile": {
        "name": "file/filename.jpg",
        "type": "image/jpeg"
    },
    "media_url_prefix": "/media/",
    "uploader_id": 1,
    "filesize": "1 kB",
    "timestamp": "2016-01-24T08:38:28.698988"
}
```
Then I could use the angular filter for type, e.g. ` | filter: {filetype: 'application/pdf'` which does not accept point separators like `| filter: {mediafile.type: ...}`.

**Comment by normanjaeckel** [comment]
Pull request is ok (not tested).

@emanuelschuetze You can change the serializer if you like:

```python
class MediafileSerializer(ModelSerializer):
    ...
    filename = SerializerMethodField()
    filetype = SerializerMethodField()

    ...
    def get_filename(self, mediafile):
        return mediafile.name

    def get_filetype(self, mediafile):
        return mimetypes.guess_type(value.path)[0]
```

**Comment by ostcar** [comment]
ok. You have to rebase to merge it

**Comment by emanuelschuetze** [comment]
Added last fixes. All done now. Rebased. Ready for merge.

**Comment by emanuelschuetze** [comment]
@normanjaeckel I did not changed the serializer - but I just added a filetype property in the DS Model. Filter works now.

**Pull request merged**
