### PR TITLE
Directories and access permissions for mediafiles

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by tsiegleauq** [comment]
rebased on current master

**Comment by FinnStutzenstein** [comment]
@tsiegleauq Rebased and adopted `os-search-value-selector` changes.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein I get a server error after migrate existing database and login:
```
Exception inside application: 'inherited_access_groups_id'
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/sessions.py", line 179, in __call__
    return await self.inner(receive, self.send)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/utils.py", line 52, in await_many_dispatch
    await dispatch(result)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/websocket.py", line 51, in receive
    await self.receive_json(json.loads(text_data), **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/websocket.py", line 148, in receive_json
    self, content["content"], id=content["id"]
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/core/websocket.py", line 121, in receive_content
    consumer.scope["user"]["id"], requested_change_id
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/websocket.py", line 248, in get_element_data
    user_id, change_id, current_change_id
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/cache.py", line 389, in get_restricted_data
    return (await self.get_all_restricted_data(user_id), [])
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/cache.py", line 366, in get_all_restricted_data
    elements = await restricter(user_id, full_data)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/models.py", line 161, in restrict_elements
    return await cls.get_access_permissions().get_restricted_data(elements, user_id)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/mediafiles/access_permissions.py", line 26, in get_restricted_data
    access_groups = full["inherited_access_groups_id"]
  'inherited_access_groups_id'
```

**Comment by emanuelschuetze** [comment]
>  I get a server error after migrate existing database and login:

Fixed by flushing redis. Sorry.

**Comment by tsiegleauq** [comment]
Done

**Pull request merged**
