### PR TITLE
External autoupdate service

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
TODO:
- [x] Add *.pem to .gitignore

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Ping: You can use it for test instances.

@tsiegleauq I do not know why git put your commit in here...

**Comment by tsiegleauq** [comment]
improperly rebased. The commit belongs to:
https://github.com/OpenSlides/OpenSlides/pull/5534
which you approved a few hours ago and was merged. Rebasing on current master should solve the problem.

**Comment by FinnStutzenstein** [comment]
> Rebasing on current master should solve the problem. 

It doesn't. I wonder myself: The commit id changed. But I didn't even touched this commit.  I just squashed the wip-ones...

**Comment by tsiegleauq** [comment]
That's odd. Perhaps just remove it. It was merged anyways.

**Comment by FinnStutzenstein** [comment]
It doesn't even show up on `git log` or `git rebase -i`. This is the graph view:

```
* 822632737 (HEAD -> externalAutoupdateService, origin/externalAutoupdateService) Dev- and Prod-Setup and small fixes:
* 2d30af5fd https
* 7f2f72abe client fixes
* 2e1f655b9 Autoupdate throttling
* ef62628cc first changes for the projector, remove server projector code
* ef7e83c8c Keep alive packages, Notify, disabled autoupdate injecting, fixed missing await
* 2c21fe127 removing channels. Going back to a wsgi deployment
* c29f043f9 Fix projector in client and ready key in cache
* 3e4055a1d OpenSlides3+: External Autoupdate Service
| * 4c2493a85 (origin/os3+export, os3+export) Export test data for OS3+
|/  
*   991c08d57 (upstream/master, master) Merge pull request #5534 from tsiegleauq/protected-values-cause-user-error
```
-> It seems that my local repo and the github one are not synced properly... This is so weird

**Comment by FinnStutzenstein** [comment]
TODO: edit the gh actions.

**Pull request merged**
